-- Sentinel migration for the app-layer edge backfill.
--
-- The actual backfill (items.parent_id → parent-of edges, items.thread_id →
-- in-thread edges with position, metadata.about → about edges) runs as a
-- TypeScript script after Drizzle applies the 0009 marker, so UUID generation
-- stays consistent between dialects (Postgres has gen_random_uuid(); SQLite
-- doesn't). See `packages/server/scripts/backfill-edges.ts`.
--
-- The migrate CLI (`pnpm --filter @mymehq/server run migrate`) auto-invokes
-- the script; re-running is idempotent (rows are skipped if an equivalent
-- edge already exists).
SELECT 1;
