-- An edge carries the version a client read.
--
-- Two devices editing one edge overwrote each other in silence: the update
-- replaced properties unconditionally, so the loser was never told and the
-- winner was never asked. This column is what a client names on `PATCH
-- /edges/{id}` to say which state its edit was computed from.
--
-- Additive, defaulted, no backfill, no index, no constraint. Every existing
-- row reads 1, which is the correct answer rather than a placeholder: a row
-- nobody has updated since versions existed has been through exactly one
-- write. A non-volatile default is recorded in the catalog rather than
-- rewritten across the table, so this is cheap on a large edges table.
--
-- Safe to land ahead of the code that reads it. Both dialect stores name an
-- explicit column list on insert and an explicit set clause on update, and
-- neither mentions this column before the build that introduces it, so an
-- old replica serving the migrated schema writes new rows at the default and
-- leaves the column alone on an update. An edge updated during that window
-- whose version did not move is the deploy, not a defect.
ALTER TABLE "edges" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;
