-- The client-credentials grant is gone, and so is the column that held its
-- ceiling.
--
-- A machine acting on a space is an API key: minted into that space by a
-- person or by a key, and listed, narrowed, revoked and rotated on the keys
-- page. A client-credentials token has none of that. It carries no space of
-- its own, no consent row, nothing on the security page, and no way for the
-- person accountable for it to end it, and it would hold space permissions no
-- screen ever showed anybody. So the grant is removed rather than bound to a
-- space: registration refuses it and the token endpoint answers
-- `unsupported_grant_type`.
--
-- `client_credentials_scopes` was the per-client ceiling that grant read.
-- Nothing else reads it and nothing in this estate ever registered such a
-- client, so the column is dropped rather than left as a shape a later reader
-- would take for a live one.
ALTER TABLE "auth_oauth_client" DROP COLUMN IF EXISTS "client_credentials_scopes";
