// Code generated by scripts/generate-schema-sql.ts; DO NOT EDIT.
//
// SCHEMA_SQL is the fresh-database bootstrap path. It runs every server
// boot via createConnection() and must stay in sync with the Drizzle
// migrations under drizzle/<dialect>/. To refresh, run:
//   pnpm --filter @withmarfa/server schema-sql:generate
// (or implicitly via migrate:<dialect>:generate when a new migration lands).
//
// Hand-edits to this file will be overwritten on the next regen and will
// fail the schema-sql-freshness CI check.

export const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS \`api_keys\` (
	\`id\` text PRIMARY KEY NOT NULL,
	"space_id" text,
	\`key_hash\` text NOT NULL,
	\`label\` text NOT NULL,
	\`role\` text DEFAULT 'member' NOT NULL,
	\`type_permissions\` text DEFAULT '{"*":"write"}' NOT NULL,
	\`extension_permissions\` text DEFAULT '{}' NOT NULL,
	\`created_at\` text NOT NULL,
	\`revoked_at\` text,
	\`last_used_at\` text
, \`source\` text NOT NULL DEFAULT '', \`edge_permissions\` text NOT NULL DEFAULT '{}', \`default_tier\` text NOT NULL DEFAULT 'library', \`is_platform\` integer NOT NULL DEFAULT 0, \`metadata_permissions\` text NOT NULL DEFAULT '{}', \`is_runtime_credential\` integer NOT NULL DEFAULT 0, \`connection_id\` text, \`expires_at\` text, \`item_source\` text);

CREATE TABLE IF NOT EXISTS \`audit_log\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`timestamp\` text NOT NULL,
	\`key_id\` text,
	\`action\` text NOT NULL,
	\`resource_type\` text NOT NULL,
	\`resource_id\` text,
	\`details\` text DEFAULT '{}' NOT NULL
, "space_id" text);

CREATE TABLE IF NOT EXISTS "space_quotas" (
  "space_id" text PRIMARY KEY NOT NULL,
  \`items_limit\` integer,
  \`webhooks_limit\` integer,
  \`blobs_limit\` integer,
  \`storage_bytes_limit\` integer,
  \`rate_per_minute_limit\` integer,
  \`updated_at\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS "enrichment_state" (
  "item_id" TEXT PRIMARY KEY NOT NULL REFERENCES "items"("id") ON DELETE CASCADE,
  "space_id" TEXT,
  "blob_ref" TEXT NOT NULL,
  "extractor_version" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "error" TEXT,
  "updated_at" TEXT NOT NULL
, "config_signature" TEXT);

CREATE TABLE IF NOT EXISTS \`metadata\` (
	\`item_id\` text PRIMARY KEY NOT NULL,
	\`tags\` text DEFAULT '[]' NOT NULL,
	\`extensions\` text DEFAULT '{}' NOT NULL,
	FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`auth_jwks\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`public_key\` text NOT NULL,
	\`private_key\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`expires_at\` integer
, \`alg\` text, \`crv\` text);

CREATE TABLE IF NOT EXISTS "oauth_device_codes" (
  \`id\` text PRIMARY KEY NOT NULL,
  \`device_code_hash\` text NOT NULL,
  \`user_code\` text NOT NULL,
  \`client_id\` text NOT NULL,
  \`scope\` text NOT NULL,
  \`status\` text DEFAULT 'pending' NOT NULL,
  \`connection_item_id\` text,
  \`expires_at\` text NOT NULL,
  \`interval_seconds\` integer DEFAULT 5 NOT NULL,
  \`last_polled_at\` text,
  \`approved_at\` text,
  \`created_at\` text NOT NULL,
  FOREIGN KEY (\`connection_item_id\`) REFERENCES \`items\`(\`id\`) ON UPDATE no action ON DELETE set null
);

CREATE TABLE IF NOT EXISTS "bulk_action_jobs" (
  "id" TEXT PRIMARY KEY NOT NULL,
  "space_id" TEXT,
  "api_key_id" TEXT,
  "status" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "input" TEXT NOT NULL,
  "matched_ids" TEXT NOT NULL,
  "matched_count" INTEGER NOT NULL DEFAULT 0,
  "processed_count" INTEGER NOT NULL DEFAULT 0,
  "succeeded_count" INTEGER NOT NULL DEFAULT 0,
  "errored_count" INTEGER NOT NULL DEFAULT 0,
  "result" TEXT,
  "error" TEXT,
  "worker_id" TEXT,
  "worker_heartbeat_at" TEXT,
  "idempotency_key" TEXT,
  "created_at" TEXT NOT NULL,
  "started_at" TEXT,
  "finished_at" TEXT
);

CREATE TABLE IF NOT EXISTS \`inbound_webhooks\` (
  \`id\` text PRIMARY KEY NOT NULL,
  "space_id" text,
  \`connection_id\` text NOT NULL,
  \`external_service_id\` text,
  \`secret_encrypted\` text NOT NULL,
  \`verification_method\` text NOT NULL,
  \`verification_adapter_id\` text,
  \`events\` text DEFAULT '[]' NOT NULL,
  \`disabled\` integer DEFAULT 0 NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS "spaces" (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text,
	\`created_at\` text NOT NULL
, \`config\` text, \`status\` text NOT NULL DEFAULT 'active');

CREATE TABLE IF NOT EXISTS \`settings\` (
  \`key\` text PRIMARY KEY NOT NULL,
  \`value\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS \`users\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text,
	\`provider\` text NOT NULL,
	\`provider_id\` text NOT NULL,
	"space_id" text NOT NULL,
	\`created_at\` text NOT NULL,
	\`updated_at\` text NOT NULL, \`handle\` text, \`first_name\` text, \`last_name\` text, \`bio\` text, \`avatar_blob_hash\` text, \`auth_user_id\` text, \`role\` text NOT NULL DEFAULT 'member', \`timezone\` text,
	FOREIGN KEY ("space_id") REFERENCES "spaces"(\`id\`) ON UPDATE no action ON DELETE no action
);

CREATE TABLE IF NOT EXISTS \`rate_limit_windows\` (
  \`family\` text NOT NULL,
  \`window_key\` text NOT NULL,
  \`count\` integer NOT NULL,
  \`expires_at\` text NOT NULL,
  PRIMARY KEY(\`family\`, \`window_key\`)
);

CREATE TABLE IF NOT EXISTS \`versions\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`item_id\` text NOT NULL,
	\`version\` integer NOT NULL,
	\`properties\` text NOT NULL,
	\`created_at\` text NOT NULL,
	"device" text,
	FOREIGN KEY (\`item_id\`) REFERENCES \`items\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS "outbound_webhook_deliveries" (
	\`id\` text PRIMARY KEY NOT NULL,
	\`webhook_id\` text NOT NULL,
	\`event\` text NOT NULL,
	\`status_code\` integer,
	\`attempt\` integer NOT NULL,
	"succeeded" integer DEFAULT 0 NOT NULL,
	\`error\` text,
	\`created_at\` text NOT NULL,
	\`next_attempt_at\` text,
	\`payload\` text,
	\`webhook_url\` text,
	\`webhook_secret\` text,
	\`max_attempts\` integer DEFAULT 4 NOT NULL,
	\`status\` text DEFAULT 'pending' NOT NULL
);

CREATE TABLE IF NOT EXISTS "outbound_webhooks" (
	\`id\` text PRIMARY KEY NOT NULL,
	"space_id" text,
	\`url\` text NOT NULL,
	\`secret\` text NOT NULL,
	\`events\` text DEFAULT '[]' NOT NULL,
	\`type_filter\` text,
	\`active\` integer DEFAULT 1 NOT NULL,
	\`created_at\` text NOT NULL,
	\`updated_at\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS \`edges\` (
	\`id\` text PRIMARY KEY NOT NULL,
	"space_id" text,
	\`source_id\` text NOT NULL,
	\`target_id\` text NOT NULL,
	\`edge_type\` text NOT NULL,
	\`properties\` text DEFAULT '{}' NOT NULL,
	\`created_at\` text NOT NULL,
	\`updated_at\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS "event_log" (
  \`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  \`event_type\` text NOT NULL,
  \`item_id\` text,
  \`edge_id\` text,
  "space_id" text,
  \`payload\` text NOT NULL,
  \`created_at\` text NOT NULL
, \`originating_connection_id\` text, \`hop_count\` integer NOT NULL DEFAULT 0);

CREATE TABLE IF NOT EXISTS \`auth_user\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text NOT NULL,
	\`email\` text NOT NULL,
	\`email_verified\` integer DEFAULT 0 NOT NULL,
	\`image\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
, \`deletion_state\` text NOT NULL DEFAULT 'active', \`pending_deletion_at\` text);

CREATE TABLE IF NOT EXISTS \`auth_session\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`token\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL,
	\`ip_address\` text,
	\`user_agent\` text,
	\`user_id\` text NOT NULL,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`auth_account\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`account_id\` text NOT NULL,
	\`provider_id\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`access_token\` text,
	\`refresh_token\` text,
	\`id_token\` text,
	\`access_token_expires_at\` integer,
	\`refresh_token_expires_at\` integer,
	\`scope\` text,
	\`password\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL, \`issuer\` text,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`auth_verification\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`identifier\` text NOT NULL,
	\`value\` text NOT NULL,
	\`expires_at\` integer NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);

CREATE TABLE IF NOT EXISTS \`auth_passkey\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`name\` text,
	\`public_key\` text NOT NULL,
	\`user_id\` text NOT NULL,
	\`credential_id\` text NOT NULL,
	\`counter\` integer NOT NULL,
	\`device_type\` text NOT NULL,
	\`backed_up\` integer NOT NULL,
	\`transports\` text,
	\`created_at\` integer,
	\`aaguid\` text,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`inbound_webhook_events\` (
  \`id\` text PRIMARY KEY NOT NULL,
  \`inbound_webhook_id\` text NOT NULL,
  \`external_delivery_id\` text NOT NULL,
  \`received_at\` text NOT NULL,
  \`payload\` text NOT NULL,
  \`verified\` integer NOT NULL,
  \`processed_at\` text,
  \`processing_error\` text,
  \`retry_count\` integer DEFAULT 0 NOT NULL,
  \`next_attempt_at\` text
);

CREATE TABLE IF NOT EXISTS \`connection_oauth_tokens\` (
  \`id\` text PRIMARY KEY NOT NULL,
  \`connection_id\` text NOT NULL,
  "space_id" text,
  \`access_token_encrypted\` text NOT NULL,
  \`refresh_token_encrypted\` text,
  \`expires_at\` text NOT NULL,
  \`scopes\` text DEFAULT '[]' NOT NULL,
  \`previous_refresh_hash\` text,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS \`connection_leased_tokens\` (
  \`id\` text PRIMARY KEY NOT NULL,
  \`connection_id\` text NOT NULL,
  "space_id" text,
  \`capability_id\` text NOT NULL,
  \`lease_token_hash\` text NOT NULL,
  \`scopes\` text DEFAULT '[]' NOT NULL,
  \`expires_at\` text NOT NULL,
  \`revoked_at\` text,
  \`issued_by_key_id\` text,
  \`created_at\` text NOT NULL
);

CREATE TABLE IF NOT EXISTS "blobs" (
  "space_id" text NOT NULL DEFAULT '',
  \`hash\` text NOT NULL,
  \`mime_type\` text NOT NULL,
  \`size\` integer NOT NULL,
  \`storage_path\` text NOT NULL,
  PRIMARY KEY ("space_id", \`hash\`)
);

CREATE TABLE IF NOT EXISTS \`auth_oauth_client\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`client_id\` text NOT NULL,
	\`client_secret\` text,
	\`disabled\` integer DEFAULT 0 NOT NULL,
	\`skip_consent\` integer,
	\`enable_end_session\` integer,
	\`subject_type\` text,
	\`scopes\` text,
	\`user_id\` text,
	\`created_at\` integer,
	\`updated_at\` integer,
	\`name\` text,
	\`uri\` text,
	\`icon\` text,
	\`contacts\` text,
	\`tos\` text,
	\`policy\` text,
	\`software_id\` text,
	\`software_version\` text,
	\`software_statement\` text,
	\`redirect_uris\` text NOT NULL,
	\`post_logout_redirect_uris\` text,
	\`token_endpoint_auth_method\` text,
	\`grant_types\` text,
	\`response_types\` text,
	\`public\` integer,
	\`type\` text,
	\`require_pkce\` integer,
	\`reference_id\` text,
	\`metadata\` text, \`application_type\` text, \`backchannel_logout_session_required\` integer, \`backchannel_logout_uri\` text, \`client_credentials_scopes\` text, \`client_discovery_id\` text, \`dpop_bound_access_tokens\` integer, \`jwks\` text, \`jwks_uri\` text,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`auth_oauth_refresh_token\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`token\` text NOT NULL,
	\`client_id\` text NOT NULL,
	\`session_id\` text,
	\`user_id\` text NOT NULL,
	\`reference_id\` text,
	\`expires_at\` integer,
	\`created_at\` integer,
	\`revoked\` integer,
	\`auth_time\` integer,
	\`scopes\` text NOT NULL, \`authorization_code_id\` text, \`confirmation\` text, \`requested_user_info_claims\` text, \`resources\` text, \`rotated_at\` integer, \`rotation_replay_expires_at\` integer, \`rotation_replay_response\` text,
	FOREIGN KEY (\`session_id\`) REFERENCES \`auth_session\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`auth_oauth_access_token\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`token\` text NOT NULL,
	\`client_id\` text NOT NULL,
	\`session_id\` text,
	\`user_id\` text,
	\`reference_id\` text,
	\`refresh_id\` text,
	\`expires_at\` integer,
	\`created_at\` integer,
	\`scopes\` text NOT NULL, \`authorization_code_id\` text, \`confirmation\` text, \`requested_user_info_claims\` text, \`resources\` text, \`revoked\` integer,
	FOREIGN KEY (\`session_id\`) REFERENCES \`auth_session\`(\`id\`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (\`refresh_id\`) REFERENCES \`auth_oauth_refresh_token\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS \`auth_oauth_consent\` (
	\`id\` text PRIMARY KEY NOT NULL,
	\`client_id\` text NOT NULL,
	\`user_id\` text,
	\`reference_id\` text,
	\`scopes\` text NOT NULL,
	\`created_at\` integer,
	\`updated_at\` integer, \`requested_user_info_claims\` text, \`resources\` text,
	FOREIGN KEY (\`user_id\`) REFERENCES \`auth_user\`(\`id\`) ON UPDATE no action ON DELETE cascade
);

CREATE TABLE IF NOT EXISTS "custom_types" (
  "space_id" text NOT NULL DEFAULT '',
  \`id\` text NOT NULL,
  \`schema\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY ("space_id", \`id\`)
);

CREATE TABLE IF NOT EXISTS "custom_edge_types" (
  "space_id" text NOT NULL DEFAULT '',
  \`id\` text NOT NULL,
  \`schema\` text NOT NULL,
  \`created_at\` text NOT NULL,
  \`updated_at\` text NOT NULL,
  PRIMARY KEY ("space_id", \`id\`)
);

CREATE TABLE IF NOT EXISTS "items" (
	\`id\` text PRIMARY KEY NOT NULL,
	\`space_id\` text,
	\`type\` text NOT NULL,
	\`state\` text DEFAULT 'active' NOT NULL,
	\`properties\` blob NOT NULL,
	\`created_at\` text NOT NULL,
	\`updated_at\` text NOT NULL,
	\`timestamp\` text NOT NULL,
	\`source\` text,
	\`source_id\` text,
	\`version\` integer DEFAULT 1 NOT NULL,
	\`schema_version\` integer,
	\`device\` text,
	\`capture_latitude\` real,
	\`capture_longitude\` real,
	\`tier\` text DEFAULT 'library' NOT NULL
, "starts_at_utc" text, "ends_at_utc" text);

CREATE UNIQUE INDEX IF NOT EXISTS \`api_keys_key_hash_unique\` ON \`api_keys\` (\`key_hash\`);

CREATE INDEX IF NOT EXISTS \`idx_api_keys_connection_id\` ON \`api_keys\` (\`connection_id\`) WHERE \`connection_id\` IS NOT NULL;

CREATE INDEX IF NOT EXISTS \`idx_api_keys_runtime_credential\`
  ON \`api_keys\` (\`is_runtime_credential\`)
  WHERE \`is_runtime_credential\`;

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_api_keys_source_per_space\` ON \`api_keys\` (\`space_id\`, \`source\`) WHERE revoked_at IS NULL;

CREATE INDEX IF NOT EXISTS \`idx_audit_log_action\` ON \`audit_log\` (\`action\`);

CREATE INDEX IF NOT EXISTS \`idx_audit_log_resource_type\` ON \`audit_log\` (\`resource_type\`);

CREATE INDEX IF NOT EXISTS \`idx_audit_log_space_id\` ON \`audit_log\` (\`space_id\`);

CREATE INDEX IF NOT EXISTS \`idx_audit_log_timestamp\` ON \`audit_log\` (\`timestamp\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_auth_account_issuer_account_id\`
  ON \`auth_account\` (\`issuer\`, \`account_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_auth_account_provider\` ON \`auth_account\` (\`provider_id\`,\`account_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_account_user_id\` ON \`auth_account\` (\`user_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`auth_oauth_access_token_token_unique\` ON \`auth_oauth_access_token\` (\`token\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_access_token_authorization_code_id\`
  ON \`auth_oauth_access_token\` (\`authorization_code_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_access_token_client_id\` ON \`auth_oauth_access_token\` (\`client_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_auth_oauth_access_token_token\` ON \`auth_oauth_access_token\` (\`token\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_access_token_user_id\` ON \`auth_oauth_access_token\` (\`user_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`auth_oauth_client_client_id_unique\` ON \`auth_oauth_client\` (\`client_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_auth_oauth_client_client_id\` ON \`auth_oauth_client\` (\`client_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_client_reference_id\` ON \`auth_oauth_client\` (\`reference_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_client_user_id\` ON \`auth_oauth_client\` (\`user_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_consent_reference_id\` ON \`auth_oauth_consent\` (\`reference_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`uq_auth_oauth_consent_client_user\`
  ON \`auth_oauth_consent\` (\`client_id\`, \`user_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_refresh_token_authorization_code_id\`
  ON \`auth_oauth_refresh_token\` (\`authorization_code_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_refresh_token_client_id\` ON \`auth_oauth_refresh_token\` (\`client_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_refresh_token_token\` ON \`auth_oauth_refresh_token\` (\`token\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_oauth_refresh_token_user_id\` ON \`auth_oauth_refresh_token\` (\`user_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_passkey_credential_id\` ON \`auth_passkey\` (\`credential_id\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_passkey_user_id\` ON \`auth_passkey\` (\`user_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`auth_session_token_unique\` ON \`auth_session\` (\`token\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_auth_session_token\` ON \`auth_session\` (\`token\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_session_user_id\` ON \`auth_session\` (\`user_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`auth_user_email_unique\` ON \`auth_user\` (\`email\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_auth_user_email\` ON \`auth_user\` (\`email\`);

CREATE INDEX IF NOT EXISTS \`idx_auth_verification_identifier\` ON \`auth_verification\` (\`identifier\`);

CREATE INDEX IF NOT EXISTS "idx_bulk_action_jobs_gc"
  ON "bulk_action_jobs" ("status", "finished_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_bulk_action_jobs_idempotency"
  ON "bulk_action_jobs" ("space_id", "idempotency_key")
  WHERE "idempotency_key" IS NOT NULL;

CREATE INDEX IF NOT EXISTS \`idx_bulk_action_jobs_space_id\` ON \`bulk_action_jobs\` (\`space_id\`);

CREATE INDEX IF NOT EXISTS "idx_bulk_action_jobs_status"
  ON "bulk_action_jobs" ("status");

CREATE INDEX IF NOT EXISTS \`idx_connection_leased_tokens_connection_id\` ON \`connection_leased_tokens\` (\`connection_id\`, \`expires_at\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_connection_leased_tokens_hash\` ON \`connection_leased_tokens\` (\`lease_token_hash\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_connection_oauth_tokens_connection_id\` ON \`connection_oauth_tokens\` (\`connection_id\`);

CREATE INDEX IF NOT EXISTS \`idx_edges_source\` ON \`edges\` ("space_id",\`source_id\`,\`edge_type\`);

CREATE INDEX IF NOT EXISTS \`idx_edges_target\` ON \`edges\` ("space_id",\`target_id\`,\`edge_type\`);

CREATE INDEX IF NOT EXISTS \`idx_event_log_created_at\` ON \`event_log\` (\`created_at\`);

CREATE INDEX IF NOT EXISTS \`idx_event_log_edge_id\` ON \`event_log\` (\`edge_id\`);

CREATE INDEX IF NOT EXISTS \`idx_event_log_originating_connection_id\` ON \`event_log\` (\`originating_connection_id\`, \`id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_inbound_webhook_events_dedup\` ON \`inbound_webhook_events\` (\`inbound_webhook_id\`, \`external_delivery_id\`);

CREATE INDEX IF NOT EXISTS \`idx_inbound_webhook_events_pending\` ON \`inbound_webhook_events\` (\`next_attempt_at\`) WHERE \`processed_at\` IS NULL AND \`processing_error\` IS NULL;

CREATE INDEX IF NOT EXISTS \`idx_inbound_webhooks_connection_id\` ON \`inbound_webhooks\` (\`connection_id\`);

CREATE INDEX IF NOT EXISTS \`idx_items_created_at\` ON \`items\` (\`created_at\`);

CREATE INDEX IF NOT EXISTS "idx_items_enrichment_candidates" ON "items" ("updated_at")
  WHERE ("type" = 'core.file' OR "type" LIKE 'core.file.%')
    AND "state" <> 'trashed'
    AND json_extract("properties", '$.blob_ref') IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_items_source_dedup\`
  ON \`items\` (COALESCE(\`space_id\`, ''), \`source\`, \`source_id\`)
  WHERE source IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_items_source_id_prefix"
  ON "items" ("space_id", "source_id" COLLATE NOCASE)
  WHERE "source_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_items_starts_at_utc"
  ON "items" ("space_id", "starts_at_utc")
  WHERE starts_at_utc IS NOT NULL;

CREATE INDEX IF NOT EXISTS \`idx_items_state\` ON \`items\` (\`state\`);

CREATE INDEX IF NOT EXISTS \`idx_items_timestamp\` ON \`items\` (\`timestamp\`);

CREATE INDEX IF NOT EXISTS \`idx_items_type\` ON \`items\` (\`type\`);

CREATE INDEX IF NOT EXISTS \`idx_oauth_device_codes_status\` ON \`oauth_device_codes\` (\`status\`);

CREATE INDEX IF NOT EXISTS \`idx_oauth_device_codes_user_code\` ON \`oauth_device_codes\` (\`user_code\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`oauth_device_codes_device_code_hash_unique\` ON \`oauth_device_codes\` (\`device_code_hash\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`oauth_device_codes_user_code_unique\` ON \`oauth_device_codes\` (\`user_code\`);

CREATE INDEX IF NOT EXISTS \`idx_outbound_webhook_deliveries_pending\` ON \`outbound_webhook_deliveries\` (\`next_attempt_at\`) WHERE \`status\` = 'pending';

CREATE INDEX IF NOT EXISTS \`idx_outbound_webhook_deliveries_webhook_id\` ON \`outbound_webhook_deliveries\` (\`webhook_id\`);

CREATE INDEX IF NOT EXISTS \`idx_rate_limit_windows_expires_at\`
  ON \`rate_limit_windows\` (\`expires_at\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_users_auth_user_id\` ON \`users\` (\`auth_user_id\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_users_handle\` ON \`users\` (\`handle\`);

CREATE UNIQUE INDEX IF NOT EXISTS \`idx_users_provider\` ON \`users\` (\`provider\`,\`provider_id\`);

CREATE INDEX IF NOT EXISTS \`idx_versions_item_id\` ON \`versions\` (\`item_id\`);
`;
