version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/server"
      - "/packages/sdk"
      - "/packages/shared"
      - "/packages/types"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      dev-dependencies:
        dependency-type: "development"
      prod-dependencies:
        dependency-type: "production"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
