// Code generated by scripts/generate-schema-sql.ts; DO NOT EDIT.
//
// SCHEMA_SQL is the fresh-database bootstrap path. It runs every server
// boot via createConnection() and must stay in sync with the Drizzle
// migrations under drizzle/<dialect>/. To refresh, run:
//   pnpm --filter @mymehq/server schema-sql:generate
// (or implicitly via migrate:<dialect>:generate when a new migration lands).
//
// Hand-edits to this file will be overwritten on the next regen and will
// fail the schema-sql-freshness CI check.

export const SCHEMA_SQL = `
-- T-145: SCHEMA_SQL is auto-generated. The myme_app role + grants are
-- reconstructed from information_schema because pg_dump --no-privileges
-- strips them. The role is emitted first (RLS policies reference it);
-- table grants are emitted after the pg_dump body (tables must exist).
--
-- T-168: grant the connection user MEMBERSHIP in myme_app so SET ROLE
-- succeeds during request handling. PG 16+ no longer auto-grants
-- membership on CREATE ROLE; the creator gets admin option but must
-- explicitly GRANT for the role to be settable via SET ROLE. The inner
-- BEGIN/EXCEPTION wrapper makes the GRANT idempotent and survives
-- running as a user without admin option (raises NOTICE rather than
-- aborting the bootstrap — an operator with sufficient privilege must
-- then run the GRANT once).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'myme_app') THEN
    CREATE ROLE "myme_app";
  END IF;
  BEGIN
    -- quote_ident() is the identifier-injection safety boundary —
    -- current_user is a built-in PG function returning a name, but
    -- composing it into the GRANT via EXECUTE means we must quote it
    -- explicitly. Don't simplify to plain interpolation.
    EXECUTE 'GRANT myme_app TO ' || quote_ident(current_user);
  EXCEPTION
    WHEN insufficient_privilege THEN
      RAISE NOTICE
        'Could not GRANT myme_app TO %: %. An operator with admin option on myme_app (or a superuser) must run this once before tenant-scoped requests will succeed.',
        current_user, SQLERRM;
  END;
END
$$;
GRANT USAGE ON SCHEMA public TO "myme_app";

CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.api_keys (
    id text NOT NULL,
    tenant_id text,
    key_hash text NOT NULL,
    label text NOT NULL,
    role text DEFAULT 'member'::text NOT NULL,
    type_permissions text DEFAULT '{"*":"write"}'::text NOT NULL,
    extension_permissions text DEFAULT '{}'::text NOT NULL,
    created_at text NOT NULL,
    revoked_at text,
    last_used_at text,
    source text NOT NULL,
    edge_permissions text DEFAULT '{}'::text NOT NULL,
    default_tier text DEFAULT 'library'::text NOT NULL,
    is_platform boolean DEFAULT false NOT NULL,
    metadata_permissions text DEFAULT '{}'::text NOT NULL,
    is_runtime_credential boolean DEFAULT false NOT NULL,
    connection_id text
);

CREATE TABLE IF NOT EXISTS public.audit_log (
    id text NOT NULL,
    "timestamp" text NOT NULL,
    key_id text,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id text,
    details text DEFAULT '{}'::text NOT NULL,
    tenant_id text
);

CREATE TABLE IF NOT EXISTS public.auth_account (
    id text NOT NULL,
    account_id text NOT NULL,
    provider_id text NOT NULL,
    user_id text NOT NULL,
    access_token text,
    refresh_token text,
    id_token text,
    access_token_expires_at timestamp without time zone,
    refresh_token_expires_at timestamp without time zone,
    scope text,
    password text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_jwks (
    id text NOT NULL,
    public_key text NOT NULL,
    private_key text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    expires_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.auth_oauth_access_token (
    id text NOT NULL,
    token text NOT NULL,
    client_id text NOT NULL,
    session_id text,
    user_id text,
    reference_id text,
    refresh_id text,
    expires_at timestamp without time zone,
    created_at timestamp without time zone,
    scopes text[] NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_oauth_client (
    id text NOT NULL,
    client_id text NOT NULL,
    client_secret text,
    disabled boolean DEFAULT false NOT NULL,
    skip_consent boolean,
    enable_end_session boolean,
    subject_type text,
    scopes text[],
    user_id text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    name text,
    uri text,
    icon text,
    contacts text[],
    tos text,
    policy text,
    software_id text,
    software_version text,
    software_statement text,
    redirect_uris text[] NOT NULL,
    post_logout_redirect_uris text[],
    token_endpoint_auth_method text,
    grant_types text[],
    response_types text[],
    public boolean,
    type text,
    require_pkce boolean,
    reference_id text,
    metadata jsonb
);

CREATE TABLE IF NOT EXISTS public.auth_oauth_consent (
    id text NOT NULL,
    client_id text NOT NULL,
    user_id text,
    reference_id text,
    scopes text[] NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.auth_oauth_refresh_token (
    id text NOT NULL,
    token text NOT NULL,
    client_id text NOT NULL,
    session_id text,
    user_id text NOT NULL,
    reference_id text,
    expires_at timestamp without time zone,
    created_at timestamp without time zone,
    revoked timestamp without time zone,
    auth_time timestamp without time zone,
    scopes text[] NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_passkey (
    id text NOT NULL,
    name text,
    public_key text NOT NULL,
    user_id text NOT NULL,
    credential_id text NOT NULL,
    counter integer NOT NULL,
    device_type text NOT NULL,
    backed_up boolean NOT NULL,
    transports text,
    created_at timestamp without time zone,
    aaguid text
);

CREATE TABLE IF NOT EXISTS public.auth_session (
    id text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    token text NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    ip_address text,
    user_agent text,
    user_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.auth_user (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    image text,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    deletion_state text DEFAULT 'active'::text NOT NULL,
    pending_deletion_at text
);

CREATE TABLE IF NOT EXISTS public.auth_verification (
    id text NOT NULL,
    identifier text NOT NULL,
    value text NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.blobs (
    hash text NOT NULL,
    mime_type text NOT NULL,
    size integer NOT NULL,
    storage_path text NOT NULL,
    tenant_id text DEFAULT ''::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.bulk_action_jobs (
    id text NOT NULL,
    tenant_id text,
    api_key_id text,
    status text NOT NULL,
    action text NOT NULL,
    input text NOT NULL,
    matched_ids text NOT NULL,
    matched_count integer DEFAULT 0 NOT NULL,
    processed_count integer DEFAULT 0 NOT NULL,
    succeeded_count integer DEFAULT 0 NOT NULL,
    errored_count integer DEFAULT 0 NOT NULL,
    result text,
    error text,
    worker_id text,
    worker_heartbeat_at text,
    idempotency_key text,
    created_at text NOT NULL,
    started_at text,
    finished_at text
);

CREATE TABLE IF NOT EXISTS public.connection_leased_tokens (
    id text NOT NULL,
    connection_id text NOT NULL,
    tenant_id text,
    capability_id text NOT NULL,
    lease_token_hash text NOT NULL,
    scopes text DEFAULT '[]'::text NOT NULL,
    expires_at text NOT NULL,
    revoked_at text,
    issued_by_key_id text,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.connection_oauth_tokens (
    id text NOT NULL,
    connection_id text NOT NULL,
    tenant_id text,
    access_token_encrypted text NOT NULL,
    refresh_token_encrypted text,
    expires_at text NOT NULL,
    scopes text DEFAULT '[]'::text NOT NULL,
    previous_refresh_hash text,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.custom_edge_types (
    id text NOT NULL,
    tenant_id text,
    schema text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.custom_types (
    id text NOT NULL,
    tenant_id text,
    schema text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.edges (
    id text NOT NULL,
    tenant_id text,
    source_id text NOT NULL,
    target_id text NOT NULL,
    edge_type text NOT NULL,
    properties text DEFAULT '{}'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.event_log (
    id bigint NOT NULL,
    event_type text NOT NULL,
    item_id text,
    tenant_id text,
    payload text NOT NULL,
    created_at text NOT NULL,
    edge_id text,
    originating_connection_id text,
    hop_count integer DEFAULT 0 NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.event_log'::regclass AND attname = 'id' AND attidentity != '') THEN
    ALTER TABLE public.event_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
        SEQUENCE NAME public.event_log_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.inbound_webhook_events (
    id text NOT NULL,
    inbound_webhook_id text NOT NULL,
    external_delivery_id text NOT NULL,
    received_at text NOT NULL,
    payload text NOT NULL,
    verified integer NOT NULL,
    processed_at text,
    processing_error text,
    retry_count integer DEFAULT 0 NOT NULL,
    next_attempt_at text
);

CREATE TABLE IF NOT EXISTS public.inbound_webhooks (
    id text NOT NULL,
    tenant_id text,
    connection_id text NOT NULL,
    external_service_id text,
    secret_encrypted text NOT NULL,
    verification_method text NOT NULL,
    verification_adapter_id text,
    events text DEFAULT '[]'::text NOT NULL,
    disabled integer DEFAULT 0 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.items (
    id text NOT NULL,
    tenant_id text,
    type text NOT NULL,
    state text DEFAULT 'active'::text NOT NULL,
    properties text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    "timestamp" text NOT NULL,
    source text,
    source_id text,
    version integer DEFAULT 1 NOT NULL,
    schema_version integer,
    device text,
    capture_latitude double precision,
    capture_longitude double precision,
    tier text DEFAULT 'library'::text NOT NULL,
    search_vector tsvector
);

CREATE TABLE IF NOT EXISTS public.metadata (
    item_id text NOT NULL,
    tags text DEFAULT '[]'::text NOT NULL,
    extensions text DEFAULT '{}'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.oauth_device_codes (
    id text NOT NULL,
    device_code_hash text NOT NULL,
    user_code text NOT NULL,
    client_id text NOT NULL,
    scope text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    connection_item_id text,
    expires_at text NOT NULL,
    interval_seconds integer DEFAULT 5 NOT NULL,
    last_polled_at text,
    approved_at text,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.outbound_webhook_deliveries (
    id text NOT NULL,
    webhook_id text NOT NULL,
    event text NOT NULL,
    status_code integer,
    attempt integer NOT NULL,
    succeeded integer DEFAULT 0 NOT NULL,
    error text,
    created_at text NOT NULL,
    next_attempt_at text,
    payload text,
    webhook_url text,
    webhook_secret text,
    max_attempts integer DEFAULT 4 NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.outbound_webhooks (
    id text NOT NULL,
    tenant_id text,
    url text NOT NULL,
    secret text NOT NULL,
    events text DEFAULT '[]'::text NOT NULL,
    type_filter text,
    active integer DEFAULT 1 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.rate_limit_windows (
    family text NOT NULL,
    window_key text NOT NULL,
    count integer NOT NULL,
    expires_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settings (
    key text NOT NULL,
    value text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tenant_quotas (
    tenant_id text NOT NULL,
    items_limit integer,
    webhooks_limit integer,
    blobs_limit integer,
    storage_bytes_limit bigint,
    rate_per_minute_limit integer,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tenants (
    id text NOT NULL,
    name text,
    created_at text NOT NULL,
    config jsonb,
    status text DEFAULT 'active'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
    id text NOT NULL,
    name text,
    provider text NOT NULL,
    provider_id text NOT NULL,
    tenant_id text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    handle text,
    first_name text,
    last_name text,
    bio text,
    avatar_blob_hash text,
    auth_user_id text,
    role text DEFAULT 'member'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.versions (
    id text NOT NULL,
    item_id text NOT NULL,
    version integer NOT NULL,
    properties text NOT NULL,
    created_at text NOT NULL,
    device text
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.api_keys'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['key_hash']::text[]) THEN
    ALTER TABLE ONLY public.api_keys
        ADD CONSTRAINT api_keys_key_hash_unique UNIQUE (key_hash);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.api_keys'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.api_keys
        ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.audit_log'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.audit_log
        ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_account'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_account
        ADD CONSTRAINT auth_account_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_jwks'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_jwks
        ADD CONSTRAINT auth_jwks_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_access_token'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_access_token
        ADD CONSTRAINT auth_oauth_access_token_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_access_token'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['token']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_access_token
        ADD CONSTRAINT auth_oauth_access_token_token_unique UNIQUE (token);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_client'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['client_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_client
        ADD CONSTRAINT auth_oauth_client_client_id_unique UNIQUE (client_id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_client'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_client
        ADD CONSTRAINT auth_oauth_client_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_consent'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_consent
        ADD CONSTRAINT auth_oauth_consent_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_refresh_token'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_refresh_token
        ADD CONSTRAINT auth_oauth_refresh_token_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_passkey'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_passkey
        ADD CONSTRAINT auth_passkey_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_session'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_session
        ADD CONSTRAINT auth_session_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_session'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['token']::text[]) THEN
    ALTER TABLE ONLY public.auth_session
        ADD CONSTRAINT auth_session_token_unique UNIQUE (token);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_user'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['email']::text[]) THEN
    ALTER TABLE ONLY public.auth_user
        ADD CONSTRAINT auth_user_email_unique UNIQUE (email);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_user'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_user
        ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_verification'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.auth_verification
        ADD CONSTRAINT auth_verification_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.blobs'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['tenant_id', 'hash']::text[]) THEN
    ALTER TABLE ONLY public.blobs
        ADD CONSTRAINT blobs_tenant_id_hash_pk PRIMARY KEY (tenant_id, hash);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.bulk_action_jobs'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.bulk_action_jobs
        ADD CONSTRAINT bulk_action_jobs_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.connection_leased_tokens'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.connection_leased_tokens
        ADD CONSTRAINT connection_leased_tokens_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.connection_oauth_tokens'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.connection_oauth_tokens
        ADD CONSTRAINT connection_oauth_tokens_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.custom_edge_types'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.custom_edge_types
        ADD CONSTRAINT custom_edge_types_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.custom_types'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.custom_types
        ADD CONSTRAINT custom_types_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.edges'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.edges
        ADD CONSTRAINT edges_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.event_log'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.event_log
        ADD CONSTRAINT event_log_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.inbound_webhook_events'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.inbound_webhook_events
        ADD CONSTRAINT inbound_webhook_events_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.inbound_webhooks'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.inbound_webhooks
        ADD CONSTRAINT inbound_webhooks_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.items'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.items
        ADD CONSTRAINT items_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.metadata'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['item_id']::text[]) THEN
    ALTER TABLE ONLY public.metadata
        ADD CONSTRAINT metadata_pkey PRIMARY KEY (item_id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.oauth_device_codes'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['device_code_hash']::text[]) THEN
    ALTER TABLE ONLY public.oauth_device_codes
        ADD CONSTRAINT oauth_device_codes_device_code_hash_unique UNIQUE (device_code_hash);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.oauth_device_codes'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.oauth_device_codes
        ADD CONSTRAINT oauth_device_codes_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.oauth_device_codes'::regclass AND c.contype = 'u'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_code']::text[]) THEN
    ALTER TABLE ONLY public.oauth_device_codes
        ADD CONSTRAINT oauth_device_codes_user_code_unique UNIQUE (user_code);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.rate_limit_windows'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['family', 'window_key']::text[]) THEN
    ALTER TABLE ONLY public.rate_limit_windows
        ADD CONSTRAINT rate_limit_windows_family_window_key_pk PRIMARY KEY (family, window_key);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.settings'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['key']::text[]) THEN
    ALTER TABLE ONLY public.settings
        ADD CONSTRAINT settings_pkey PRIMARY KEY (key);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.tenant_quotas'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['tenant_id']::text[]) THEN
    ALTER TABLE ONLY public.tenant_quotas
        ADD CONSTRAINT tenant_quotas_pkey PRIMARY KEY (tenant_id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.tenants'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.tenants
        ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.users'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.users
        ADD CONSTRAINT users_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.versions'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.versions
        ADD CONSTRAINT versions_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.outbound_webhook_deliveries'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.outbound_webhook_deliveries
        ADD CONSTRAINT webhook_deliveries_pkey PRIMARY KEY (id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.outbound_webhooks'::regclass AND c.contype = 'p'
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['id']::text[]) THEN
    ALTER TABLE ONLY public.outbound_webhooks
        ADD CONSTRAINT webhooks_pkey PRIMARY KEY (id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_api_keys_connection_id ON public.api_keys USING btree (connection_id) WHERE (connection_id IS NOT NULL);

CREATE UNIQUE INDEX IF NOT EXISTS idx_api_keys_source_per_tenant ON public.api_keys USING btree (tenant_id, source) WHERE (revoked_at IS NULL);

CREATE INDEX IF NOT EXISTS idx_audit_log_action ON public.audit_log USING btree (action);

CREATE INDEX IF NOT EXISTS idx_audit_log_resource_type ON public.audit_log USING btree (resource_type);

CREATE INDEX IF NOT EXISTS idx_audit_log_tenant_id ON public.audit_log USING btree (tenant_id);

CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON public.audit_log USING btree ("timestamp");

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_account_provider ON public.auth_account USING btree (provider_id, account_id);

CREATE INDEX IF NOT EXISTS idx_auth_account_user_id ON public.auth_account USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_access_token_client_id ON public.auth_oauth_access_token USING btree (client_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_oauth_access_token_token ON public.auth_oauth_access_token USING btree (token);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_access_token_user_id ON public.auth_oauth_access_token USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_oauth_client_client_id ON public.auth_oauth_client USING btree (client_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_client_reference_id ON public.auth_oauth_client USING btree (reference_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_client_user_id ON public.auth_oauth_client USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_consent_reference_id ON public.auth_oauth_consent USING btree (reference_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_consent_user_client ON public.auth_oauth_consent USING btree (user_id, client_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_refresh_token_client_id ON public.auth_oauth_refresh_token USING btree (client_id);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_refresh_token_token ON public.auth_oauth_refresh_token USING btree (token);

CREATE INDEX IF NOT EXISTS idx_auth_oauth_refresh_token_user_id ON public.auth_oauth_refresh_token USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_passkey_credential_id ON public.auth_passkey USING btree (credential_id);

CREATE INDEX IF NOT EXISTS idx_auth_passkey_user_id ON public.auth_passkey USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_session_token ON public.auth_session USING btree (token);

CREATE INDEX IF NOT EXISTS idx_auth_session_user_id ON public.auth_session USING btree (user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_user_email ON public.auth_user USING btree (email);

CREATE INDEX IF NOT EXISTS idx_auth_verification_identifier ON public.auth_verification USING btree (identifier);

CREATE INDEX IF NOT EXISTS idx_bulk_action_jobs_gc ON public.bulk_action_jobs USING btree (status, finished_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bulk_action_jobs_idempotency ON public.bulk_action_jobs USING btree (tenant_id, idempotency_key) NULLS NOT DISTINCT WHERE (idempotency_key IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_bulk_action_jobs_status ON public.bulk_action_jobs USING btree (status);

CREATE INDEX IF NOT EXISTS idx_bulk_action_jobs_tenant_id ON public.bulk_action_jobs USING btree (tenant_id);

CREATE INDEX IF NOT EXISTS idx_connection_leased_tokens_connection_id ON public.connection_leased_tokens USING btree (connection_id, expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_connection_leased_tokens_hash ON public.connection_leased_tokens USING btree (lease_token_hash);

CREATE UNIQUE INDEX IF NOT EXISTS idx_connection_oauth_tokens_connection_id ON public.connection_oauth_tokens USING btree (connection_id);

CREATE INDEX IF NOT EXISTS idx_edges_source ON public.edges USING btree (tenant_id, source_id, edge_type);

CREATE INDEX IF NOT EXISTS idx_edges_target ON public.edges USING btree (tenant_id, target_id, edge_type);

CREATE INDEX IF NOT EXISTS idx_event_log_created_at ON public.event_log USING btree (created_at);

CREATE INDEX IF NOT EXISTS idx_event_log_edge_id ON public.event_log USING btree (edge_id);

CREATE INDEX IF NOT EXISTS idx_event_log_originating_connection_id ON public.event_log USING btree (originating_connection_id, id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_inbound_webhook_events_dedup ON public.inbound_webhook_events USING btree (inbound_webhook_id, external_delivery_id);

CREATE INDEX IF NOT EXISTS idx_inbound_webhook_events_pending ON public.inbound_webhook_events USING btree (next_attempt_at) WHERE ((processed_at IS NULL) AND (processing_error IS NULL));

CREATE INDEX IF NOT EXISTS idx_inbound_webhooks_connection_id ON public.inbound_webhooks USING btree (connection_id);

CREATE INDEX IF NOT EXISTS idx_items_created_at ON public.items USING btree (created_at);

CREATE INDEX IF NOT EXISTS idx_items_search_vector ON public.items USING gin (search_vector);

CREATE UNIQUE INDEX IF NOT EXISTS idx_items_source_dedup ON public.items USING btree (source, source_id) WHERE (source IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_items_state ON public.items USING btree (state);

CREATE INDEX IF NOT EXISTS idx_items_timestamp ON public.items USING btree ("timestamp");

CREATE INDEX IF NOT EXISTS idx_items_type ON public.items USING btree (type);

CREATE INDEX IF NOT EXISTS idx_oauth_device_codes_status ON public.oauth_device_codes USING btree (status);

CREATE INDEX IF NOT EXISTS idx_oauth_device_codes_user_code ON public.oauth_device_codes USING btree (user_code);

CREATE INDEX IF NOT EXISTS idx_outbound_webhook_deliveries_pending ON public.outbound_webhook_deliveries USING btree (next_attempt_at) WHERE (status = 'pending'::text);

CREATE INDEX IF NOT EXISTS idx_outbound_webhook_deliveries_webhook_id ON public.outbound_webhook_deliveries USING btree (webhook_id);

CREATE INDEX IF NOT EXISTS idx_rate_limit_windows_expires_at ON public.rate_limit_windows USING btree (expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_auth_user_id ON public.users USING btree (auth_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_handle ON public.users USING btree (handle);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_provider ON public.users USING btree (provider, provider_id);

CREATE INDEX IF NOT EXISTS idx_versions_item_id ON public.versions USING btree (item_id);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_account'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_account
        ADD CONSTRAINT auth_account_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_access_token'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_oauth_refresh_token'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['refresh_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_access_token
        ADD CONSTRAINT auth_oauth_access_token_refresh_id_auth_oauth_refresh_token_id_ FOREIGN KEY (refresh_id) REFERENCES public.auth_oauth_refresh_token(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_access_token'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_session'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['session_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_access_token
        ADD CONSTRAINT auth_oauth_access_token_session_id_auth_session_id_fk FOREIGN KEY (session_id) REFERENCES public.auth_session(id) ON DELETE SET NULL;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_access_token'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_access_token
        ADD CONSTRAINT auth_oauth_access_token_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_client'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_client
        ADD CONSTRAINT auth_oauth_client_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_consent'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_consent
        ADD CONSTRAINT auth_oauth_consent_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_refresh_token'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_session'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['session_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_refresh_token
        ADD CONSTRAINT auth_oauth_refresh_token_session_id_auth_session_id_fk FOREIGN KEY (session_id) REFERENCES public.auth_session(id) ON DELETE SET NULL;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_oauth_refresh_token'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_oauth_refresh_token
        ADD CONSTRAINT auth_oauth_refresh_token_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_passkey'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_passkey
        ADD CONSTRAINT auth_passkey_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.auth_session'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.auth_user'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['user_id']::text[]) THEN
    ALTER TABLE ONLY public.auth_session
        ADD CONSTRAINT auth_session_user_id_auth_user_id_fk FOREIGN KEY (user_id) REFERENCES public.auth_user(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.metadata'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.items'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['item_id']::text[]) THEN
    ALTER TABLE ONLY public.metadata
        ADD CONSTRAINT metadata_item_id_items_id_fk FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.oauth_device_codes'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.items'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['connection_item_id']::text[]) THEN
    ALTER TABLE ONLY public.oauth_device_codes
        ADD CONSTRAINT oauth_device_codes_connection_item_id_items_id_fk FOREIGN KEY (connection_item_id) REFERENCES public.items(id) ON DELETE SET NULL;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.users'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.tenants'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['tenant_id']::text[]) THEN
    ALTER TABLE ONLY public.users
        ADD CONSTRAINT users_tenant_id_tenants_id_fk FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint c
WHERE c.conrelid = 'public.versions'::regclass AND c.contype = 'f'
  AND c.confrelid = 'public.items'::regclass
  AND ARRAY(SELECT a.attname::text FROM unnest(c.conkey) WITH ORDINALITY AS k(attnum, ord)
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
            ORDER BY k.ord)
      = ARRAY['item_id']::text[]) THEN
    ALTER TABLE ONLY public.versions
        ADD CONSTRAINT versions_item_id_items_id_fk FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE;
  END IF;
END
$$;

ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS api_keys_tenant_isolation ON public.api_keys;
CREATE POLICY api_keys_tenant_isolation ON public.api_keys TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS audit_log_tenant_isolation ON public.audit_log;
CREATE POLICY audit_log_tenant_isolation ON public.audit_log TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.blobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS blobs_tenant_isolation ON public.blobs;
CREATE POLICY blobs_tenant_isolation ON public.blobs TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id = ''::text)));

ALTER TABLE public.bulk_action_jobs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bulk_action_jobs_tenant_isolation ON public.bulk_action_jobs;
CREATE POLICY bulk_action_jobs_tenant_isolation ON public.bulk_action_jobs TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.connection_leased_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS connection_leased_tokens_tenant_isolation ON public.connection_leased_tokens;
CREATE POLICY connection_leased_tokens_tenant_isolation ON public.connection_leased_tokens TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.connection_oauth_tokens ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS connection_oauth_tokens_tenant_isolation ON public.connection_oauth_tokens;
CREATE POLICY connection_oauth_tokens_tenant_isolation ON public.connection_oauth_tokens TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.custom_edge_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS custom_edge_types_tenant_isolation ON public.custom_edge_types;
CREATE POLICY custom_edge_types_tenant_isolation ON public.custom_edge_types TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.custom_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS custom_types_tenant_isolation ON public.custom_types;
CREATE POLICY custom_types_tenant_isolation ON public.custom_types TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.edges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS edges_tenant_isolation ON public.edges;
CREATE POLICY edges_tenant_isolation ON public.edges TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.event_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS event_log_tenant_isolation ON public.event_log;
CREATE POLICY event_log_tenant_isolation ON public.event_log TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.inbound_webhooks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inbound_webhooks_tenant_isolation ON public.inbound_webhooks;
CREATE POLICY inbound_webhooks_tenant_isolation ON public.inbound_webhooks TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS items_tenant_isolation ON public.items;
CREATE POLICY items_tenant_isolation ON public.items TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.metadata ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS metadata_tenant_isolation ON public.metadata;
CREATE POLICY metadata_tenant_isolation ON public.metadata TO myme_app USING ((EXISTS ( SELECT 1
   FROM public.items
  WHERE ((items.id = metadata.item_id) AND ((items.tenant_id = current_setting('myme.tenant_id'::text, true)) OR (items.tenant_id IS NULL))))));

ALTER TABLE public.outbound_webhooks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS outbound_webhooks_tenant_isolation ON public.outbound_webhooks;
CREATE POLICY outbound_webhooks_tenant_isolation ON public.outbound_webhooks TO myme_app USING (((tenant_id = current_setting('myme.tenant_id'::text, true)) OR (tenant_id IS NULL)));

ALTER TABLE public.versions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS versions_tenant_isolation ON public.versions;
CREATE POLICY versions_tenant_isolation ON public.versions TO myme_app USING ((EXISTS ( SELECT 1
   FROM public.items
  WHERE ((items.id = versions.item_id) AND ((items.tenant_id = current_setting('myme.tenant_id'::text, true)) OR (items.tenant_id IS NULL))))));

-- Table grants on the myme_app role (T-145; see role block above).
-- Schema-qualified (\`public.x\`) so the grants resolve regardless of
-- search_path — pg_dump emits its CREATE TABLE statements with the
-- \`public.\` prefix, and grants must match the qualified table for
-- non-default search_paths (e.g. test schemas) to apply correctly.
GRANT DELETE, INSERT, SELECT, UPDATE ON "public"."api_keys", "public"."audit_log", "public"."blobs", "public"."bulk_action_jobs", "public"."connection_leased_tokens", "public"."connection_oauth_tokens", "public"."custom_edge_types", "public"."custom_types", "public"."edges", "public"."event_log", "public"."inbound_webhook_events", "public"."inbound_webhooks", "public"."items", "public"."metadata", "public"."oauth_device_codes", "public"."outbound_webhook_deliveries", "public"."outbound_webhooks", "public"."rate_limit_windows", "public"."settings", "public"."tenant_quotas", "public"."tenants", "public"."users", "public"."versions" TO "myme_app";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "myme_app";
`;
