/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`download_blob`]
#[derive(Clone, Debug)]
pub struct DownloadBlobParams {
    /// Content-addressed `sha256:<hex>` blob hash.
    pub hash: String,
}

/// struct for passing parameters to the method [`drop_blob_location`]
#[derive(Clone, Debug)]
pub struct DropBlobLocationParams {
    /// Content-addressed `sha256:<hex>` blob hash.
    pub hash: String,
    /// A store's `id`, as `GET /blobs/stores` lists it.
    pub store: String,
}

/// struct for passing parameters to the method [`get_blob_url`]
#[derive(Clone, Debug)]
pub struct GetBlobUrlParams {
    /// Content-addressed `sha256:<hex>` blob hash.
    pub hash: String,
    /// Link lifetime in seconds, capped at 604800 (seven days), which the answer's `expires_in` reports.
    pub ttl: Option<i32>,
}

/// struct for passing parameters to the method [`list_blob_locations`]
#[derive(Clone, Debug)]
pub struct ListBlobLocationsParams {
    /// Content-addressed `sha256:<hex>` blob hash.
    pub hash: String,
}

/// struct for passing parameters to the method [`upload_blob`]
#[derive(Clone, Debug)]
pub struct UploadBlobParams {
    pub body: Vec<u8>,
}

/// struct for typed successes of method [`download_blob`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadBlobSuccess {
    Status200(Vec<u8>),
    Status206(Vec<u8>),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`drop_blob_location`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DropBlobLocationSuccess {
    Status200(models::Acknowledged),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`get_blob_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlobUrlSuccess {
    Status200(models::GetBlobUrl200Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`list_blob_locations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBlobLocationsSuccess {
    Status200(models::BlobLocationPage),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`list_blob_orphans`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBlobOrphansSuccess {
    Status200(models::BlobOrphanPage),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`list_blob_stores`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBlobStoresSuccess {
    Status200(models::BlobStorePage),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`upload_blob`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadBlobSuccess {
    Status201(models::UploadBlob201Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`download_blob`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DownloadBlobError {
    Status400(models::ValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::TypeNotPermittedRefusal),
    Status404(models::BlobNotFoundRefusal),
    Status416(models::RangeNotSatisfiableRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`drop_blob_location`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DropBlobLocationError {
    Status400(models::ValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status404(models::BlobLocationNotFoundOrBlobNotFoundRefusal),
    Status409(models::CopiesBelowMinimumRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_blob_url`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetBlobUrlError {
    Status400(models::ValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::TypeNotPermittedRefusal),
    Status404(models::BlobNotFoundRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_blob_locations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBlobLocationsError {
    Status400(models::ValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::TypeNotPermittedRefusal),
    Status404(models::BlobNotFoundRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_blob_orphans`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBlobOrphansError {
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_blob_stores`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBlobStoresError {
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`upload_blob`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UploadBlobError {
    Status400(models::ValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::TypeNotPermittedRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// Streams the bytes of a blob as `application/octet-stream` from whichever store holds them, honoring one `Range`. `HEAD` answers the same headers with no body. A hash this instance does not hold answers `404`. A working key or a signed-in app reads a blob only when an item of a type it may read, in any lifecycle state, references the blob's digest in its properties; any other blob answers `404 blob_not_found` as an unknown hash does, and a credential whose type permissions reach no type is refused `403 type_not_permitted`. The operator key reads every blob.
pub fn download_blob(
    configuration: &configuration::Configuration,
    params: DownloadBlobParams,
) -> Result<reqwest::blocking::Response, Error<DownloadBlobError>> {
    let uri_str = format!(
        "{}/blobs/{hash}",
        configuration.base_path,
        hash = crate::apis::urlencode(params.hash)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(resp)
    } else {
        let content = resp.text()?;
        let entity: Option<DownloadBlobError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Removes the copy of the blob that one store holds, and its row in the location log, only when at least `min_copies` live copies would remain; otherwise the copy stays and the door answers `409 copies_below_minimum`. A store that holds no copy, or that is not attached, answers `404 blob_location_not_found`. Operator key only.
pub fn drop_blob_location(
    configuration: &configuration::Configuration,
    params: DropBlobLocationParams,
) -> Result<ResponseContent<DropBlobLocationSuccess>, Error<DropBlobLocationError>> {
    let uri_str = format!(
        "{}/blobs/{hash}/locations/{store}",
        configuration.base_path,
        hash = crate::apis::urlencode(params.hash),
        store = crate::apis::urlencode(params.store)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<DropBlobLocationSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<DropBlobLocationError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Answers a URL a client fetches the bytes from without a credential, and `expires_in`, the seconds until it stops working. When an object store holds the blob the link is the store's own signed link, so the bytes never pass through the instance; otherwise the instance serves it. `ttl` is capped at seven days. A working key or a signed-in app reads a blob only when an item of a type it may read, in any lifecycle state, references the blob's digest in its properties; any other blob answers `404 blob_not_found` as an unknown hash does, and a credential whose type permissions reach no type is refused `403 type_not_permitted`. The operator key reads every blob. The link is checked when it is minted: it serves the bytes for its lifetime whatever happens to the credential afterwards.
pub fn get_blob_url(
    configuration: &configuration::Configuration,
    params: GetBlobUrlParams,
) -> Result<ResponseContent<GetBlobUrlSuccess>, Error<GetBlobUrlError>> {
    let uri_str = format!(
        "{}/blobs/{hash}/url",
        configuration.base_path,
        hash = crate::apis::urlencode(params.hash)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = params.ttl {
        req_builder = req_builder.query(&[("ttl", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<GetBlobUrlSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<GetBlobUrlError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// The location log for one blob: every store recorded as holding its bytes, with when the copy was recorded and when a check last found it present and intact (`verified_at`, `null` until one has). A store the configuration no longer names is shown `detached` and does not count as a copy. A working key or a signed-in app reads a blob only when an item of a type it may read, in any lifecycle state, references the blob's digest in its properties; any other blob answers `404 blob_not_found` as an unknown hash does, and a credential whose type permissions reach no type is refused `403 type_not_permitted`. The operator key reads every blob.
pub fn list_blob_locations(
    configuration: &configuration::Configuration,
    params: ListBlobLocationsParams,
) -> Result<ResponseContent<ListBlobLocationsSuccess>, Error<ListBlobLocationsError>> {
    let uri_str = format!(
        "{}/blobs/{hash}/locations",
        configuration.base_path,
        hash = crate::apis::urlencode(params.hash)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<ListBlobLocationsSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<ListBlobLocationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// The orphan report: every registered blob the last run of the `blob-orphans` housekeeping job found nothing referencing, with when a run first said so. A blob stands here for the grace period before a later run purges it, and leaves the report if something names it again. Operator key only.
pub fn list_blob_orphans(
    configuration: &configuration::Configuration,
) -> Result<ResponseContent<ListBlobOrphansSuccess>, Error<ListBlobOrphansError>> {
    let uri_str = format!("{}/blobs/orphans", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<ListBlobOrphansSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<ListBlobOrphansError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Every store the instance has attached: the disk it uploads to and, when one is configured, the object store. A store the configuration no longer names stays listed with `detached_at` set, because the location log still describes it. `min_copies` is the live copies a blob keeps at the least: a drop that would leave fewer is refused. Operator key only.
pub fn list_blob_stores(
    configuration: &configuration::Configuration,
) -> Result<ResponseContent<ListBlobStoresSuccess>, Error<ListBlobStoresError>> {
    let uri_str = format!("{}/blobs/stores", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<ListBlobStoresSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<ListBlobStoresError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Takes the raw bytes as the body, with `Content-Type` naming their MIME type, and answers `201` with the `sha256:<hex>` content-addressed hash. The body streams to disk as it arrives and has no size cap. Uploading bytes already held answers the existing hash. `multipart/form-data` is refused: send the bytes themselves. Takes write on at least one type, since an item of any type can reference a blob; a credential with none is refused `403 type_not_permitted` before the body is read. The operator key uploads without one. An upload is readable once an item references it.
pub fn upload_blob(
    configuration: &configuration::Configuration,
    params: UploadBlobParams,
) -> Result<ResponseContent<UploadBlobSuccess>, Error<UploadBlobError>> {
    let uri_str = format!("{}/blobs", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.body(params.body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<UploadBlobSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<UploadBlobError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
