/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_edge_type`]
#[derive(Clone, Debug)]
pub struct CreateEdgeTypeParams {
    pub edge_type_request: Option<models::EdgeTypeRequest>,
}

/// struct for passing parameters to the method [`delete_edge_type`]
#[derive(Clone, Debug)]
pub struct DeleteEdgeTypeParams {
    /// Edge type id.
    pub id: String,
    /// Delete the registration even though edges of the type exist, leaving them naming it.
    pub force: Option<String>,
}

/// struct for typed successes of method [`create_edge_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEdgeTypeSuccess {
    Status201(models::CreateEdgeType201Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`delete_edge_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEdgeTypeSuccess {
    Status200(models::Acknowledged),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`list_edge_types`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEdgeTypesSuccess {
    Status200(models::EdgeTypePage),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_edge_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEdgeTypeError {
    Status400(models::MissingRequiredFieldOrValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status409(models::ConflictRefusal),
    Status413(models::RequestTooLargeRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_edge_type`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEdgeTypeError {
    Status400(models::ValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status404(models::EdgeTypeNotFoundRefusal),
    Status409(models::EdgeTypeInUseRefusal),
    Status413(models::RequestTooLargeRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_edge_types`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEdgeTypesError {
    Status401(models::UnauthorizedRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// Registers an edge type with its cardinality, cascade behavior, type constraints, and optional property schema. Requires `metadata.edge_types:write`. The eight core edge-type names are reserved and reject with a conflict, and a registered edge type is flat with no inheritance.
pub fn create_edge_type(
    configuration: &configuration::Configuration,
    params: CreateEdgeTypeParams,
) -> Result<ResponseContent<CreateEdgeTypeSuccess>, Error<CreateEdgeTypeError>> {
    let uri_str = format!("{}/edge-types", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.edge_type_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<CreateEdgeTypeSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<CreateEdgeTypeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Removes a registered edge type. Requires `schema.write`; core edge types are rejected, and an edge type this instance does not hold resolves as not-found. Refused `409 edge_type_in_use` while any edge of the type is stored, the shape the sibling `DELETE /types/{id}` has for items. `?force=true` deletes the registration anyway and leaves those edges in place, still naming a type the instance no longer holds — it orphans rather than cascades, because deleting rows nobody asked to delete is the worse of the two surprises.
pub fn delete_edge_type(
    configuration: &configuration::Configuration,
    params: DeleteEdgeTypeParams,
) -> Result<ResponseContent<DeleteEdgeTypeSuccess>, Error<DeleteEdgeTypeError>> {
    let uri_str = format!(
        "{}/edge-types/{id}",
        configuration.base_path,
        id = crate::apis::urlencode(params.id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = params.force {
        req_builder = req_builder.query(&[("force", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<DeleteEdgeTypeSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<DeleteEdgeTypeError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Returns every edge type this instance resolves — the eight core types plus any registered through `POST /edge-types` — each with its cardinality, cascade behavior, and source/target type constraints.
pub fn list_edge_types(
    configuration: &configuration::Configuration,
) -> Result<ResponseContent<ListEdgeTypesSuccess>, Error<ListEdgeTypesError>> {
    let uri_str = format!("{}/edge-types", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<ListEdgeTypesSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<ListEdgeTypesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
