/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`create_owner`]
#[derive(Clone, Debug)]
pub struct CreateOwnerParams {
    pub create_owner_request: models::CreateOwnerRequest,
}

/// struct for typed successes of method [`create_owner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOwnerSuccess {
    Status201(models::Owner),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`get_owner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOwnerSuccess {
    Status200(models::Owner),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_owner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateOwnerError {
    Status400(models::MissingRequiredFieldOrValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status409(models::OwnerExistsRefusal),
    Status413(models::RequestTooLargeRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_owner`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetOwnerError {
    Status401(models::UnauthorizedRefusal),
    Status403(models::ForbiddenRefusal),
    Status404(models::OwnerNotFoundRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// Creates the one account on this instance's sign-in surface, with an email address and a password. Sign-up is disabled on every instance, so this is the only way a person comes to exist behind the consent screen, and the account can sign in at `POST /auth/sign-in/email` the moment this answers. Refused `409 owner_exists` once an owner exists, for any body the schema accepts; the password is judged by the sign-in surface's own length rule and a refusal is `400 validation_error` naming `password` and the bound. Operator key only: the operator key is what proves the person running the instance, and it outlives the bootstrap secret.
pub fn create_owner(
    configuration: &configuration::Configuration,
    params: CreateOwnerParams,
) -> Result<ResponseContent<CreateOwnerSuccess>, Error<CreateOwnerError>> {
    let uri_str = format!("{}/owner", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&params.create_owner_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<CreateOwnerSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<CreateOwnerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Answers the owner: the one account on this instance's sign-in surface, which is the person the OAuth consent screen asks. `404 owner_not_found` on an instance that has none yet, which is the state every instance boots in; `POST /owner` is what changes it. Operator key only.
pub fn get_owner(
    configuration: &configuration::Configuration,
) -> Result<ResponseContent<GetOwnerSuccess>, Error<GetOwnerError>> {
    let uri_str = format!("{}/owner", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<GetOwnerSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<GetOwnerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
