/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 2
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{ContentType, Error, configuration};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};

/// struct for passing parameters to the method [`search_items`]
#[derive(Clone, Debug)]
pub struct SearchItemsParams {
    /// Full-text search query.
    pub q: String,
    /// Restrict to a single type, subtypes included. A concrete identifier this instance does not know is refused with 400 `unknown_type`.
    pub r#type: Option<String>,
    /// Filter by lifecycle state. Omitting the parameter answers the active state, as a listing does, so a search never answers a row a listing hides. `any` widens to every state, the same sentinel the listing takes. A row in the bin is not indexed, so it is not matched under any value.
    pub state: Option<String>,
    /// Filter by tier; `all` or absent means unfiltered.
    pub tier: Option<String>,
    /// Comma-separated opt-in inclusions. `system` widens the row set to include `system.*` items, which are excluded by default. A `type` filter in the `system.` namespace, concrete or wildcard, opts in on its own without the token. It is the only token this route reads.
    pub include: Option<String>,
    /// Comma-separated tags; items must match all (AND).
    pub tags: Option<String>,
    /// Maximum results to return.
    pub limit: Option<i32>,
    /// Opaque cursor from a previous page's `next_cursor`.
    pub cursor: Option<String>,
    /// Structured filter expression, as on `GET /items`, including its edge terms and their refusals: a term naming an edge type the credential may not read is refused `403 edge_permission_denied`, and a `backref` term anchored on an item whose type it may not read is `403 type_not_permitted`.
    pub filter: Option<String>,
    /// Lower bound on the item's own time — `occurred_at`, falling back to `created_at` (exclusive). An RFC 3339 instant in any valid spelling; it is normalized before the comparison. Not the modification time.
    pub occurred_after: Option<String>,
    /// Upper bound on the item's own time — `occurred_at`, falling back to `created_at` (exclusive).
    pub occurred_before: Option<String>,
}

/// struct for typed successes of method [`search_items`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchItemsSuccess {
    Status200(models::SearchResultPage),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`search_items`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SearchItemsError {
    Status400(models::UnknownTypeOrValidationErrorRefusal),
    Status401(models::UnauthorizedRefusal),
    Status403(models::EdgePermissionDeniedOrTypeNotPermittedRefusal),
    Status429(models::RateLimitedRefusal),
    Status503(models::WriteContentionRefusal),
    UnknownValue(serde_json::Value),
}

/// Full-text search across every item the caller can read, indexing textual properties and tags, ranked by relevance with a configurable recency boost. Accepts the same filters as `GET /items` — including its two time bounds, which read the item's own time — and pages by cursor like every list: pass `next_cursor` back as `cursor`. The ranking is recomputed on every page, so a row whose score moves between two reads can be seen twice or missed; absolute scores aren't stable across index rebuilds. The ranking is read at most 10,000 rows deep, and the page that reaches that depth answers `next_cursor: null`. Unrecognized query parameters are refused with `400` rather than ignored, so a misspelled filter cannot silently return an unfiltered page. A parameter of your own — a cache-buster, an analytics tag — must start with `_`, which is always ignored.
pub fn search_items(
    configuration: &configuration::Configuration,
    params: SearchItemsParams,
) -> Result<ResponseContent<SearchItemsSuccess>, Error<SearchItemsError>> {
    let uri_str = format!("{}/search", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("q", &params.q.to_string())]);
    if let Some(ref param_value) = params.r#type {
        req_builder = req_builder.query(&[("type", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.state {
        req_builder = req_builder.query(&[("state", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.tier {
        req_builder = req_builder.query(&[("tier", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.include {
        req_builder = req_builder.query(&[("include", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.tags {
        req_builder = req_builder.query(&[("tags", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.cursor {
        req_builder = req_builder.query(&[("cursor", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.filter {
        req_builder = req_builder.query(&[("filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.occurred_after {
        req_builder = req_builder.query(&[("occurred_after", &param_value.to_string())]);
    }
    if let Some(ref param_value) = params.occurred_before {
        req_builder = req_builder.query(&[("occurred_before", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req)?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text()?;
        let entity: Option<SearchItemsSuccess> = serde_json::from_str(&content).ok();
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text()?;
        let entity: Option<SearchItemsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
