-- An item records when it entered its soft-deleted state, so the retention
-- sweep can key off that rather than off `updated_at`.
--
-- `updated_at` is the item's modification time and was never the thing the
-- sweep meant. Any write to a trashed row moves it, so editing something
-- already in the bin restarted its sixty-day clock; tag and extension writes
-- move it too, which extends that to writes nobody would call an edit. The
-- column is a proxy for the wrong thing, and the honest key is the transition
-- into the state.
--
-- Nullable, additive, no index. NULL means "not soft-deleted", which is what
-- every active row carries. The write path stamps it on the way in and clears
-- it on the way out, so a restore followed by a second delete starts a fresh
-- window instead of inheriting the first.
--
-- The backfill takes `updated_at` for rows already in the bin: that is exactly
-- what the sweep was reading for them, so no row's purge date moves on the day
-- this lands. Confined to `state = 'trashed'` because that is the only state
-- the sweep considers — a `system.*` row soft-deletes to `revoked` and is
-- swept by nothing here, so backfilling it would invent a time for a row that
-- has no use for one.
--
-- Safe to land ahead of the code that reads it: the serving build names an
-- explicit column list and never mentions this one. During the roll an old
-- replica soft-deletes a row without stamping it, and that row falls back to
-- the `updated_at` behavior it has today rather than becoming unpurgeable.
ALTER TABLE `items` ADD `trashed_at` text;--> statement-breakpoint
UPDATE `items` SET `trashed_at` = `updated_at` WHERE `state` = 'trashed';
