-- A blob row records when it was registered, so an orphan sweep can wait.
--
-- Registering a blob and creating the item that references it are two calls.
-- Between them the blob is unreferenced, which is indistinguishable from the
-- state of a blob whose item write was refused and never retried. Nothing
-- could tell those apart, so nothing could safely reclaim the second kind:
-- the sweep that finds them had no way to leave the first kind alone.
--
-- A registration stamp is what separates them. An unreferenced blob older
-- than the grace window was not mid-upload.
--
-- The default is the migration's own timestamp rather than an expression:
-- SQLite refuses a non-constant default on ADD COLUMN, and a constant is the
-- right answer anyway. Rows that predate the column were all registered
-- before this ran, so a stamp at this moment understates their age and never
-- overstates it. During the roll that follows, a replica still running the
-- previous build inserts without naming this column and gets the same value,
-- which reads as recent and is therefore protected by the grace window
-- rather than swept.
ALTER TABLE `blobs` ADD COLUMN `created_at` text NOT NULL DEFAULT '2026-09-12T23:50:00.000Z';
