/**
 * Generate `SCHEMA_SQL` for the requested dialect from the Drizzle migrations.
 *
 * SCHEMA_SQL is the fresh-database bootstrap path (T-014) that runs every
 * server boot. It must always reflect what `pnpm migrate` would produce
 * starting from `0000`. This script removes the manual three-place sync
 * burden (T-145) by applying all migrations to a temporary database and
 * dumping the resulting schema into `src/storage/<dialect>/schema-sql.generated.ts`.
 *
 * Usage:
 *   tsx scripts/generate-schema-sql.ts --dialect=sqlite
 *   bash scripts/with-temp-pg.sh tsx scripts/generate-schema-sql.ts --dialect=pg
 *
 * SQLite: applies migrations to libsql `:memory:` and dumps `sqlite_master`.
 *
 * PG: requires DATABASE_URL (set by with-temp-pg.sh, or by the CI service
 *     container). Applies all migrations, then invokes pg_dump — preferring
 *     `docker exec` into the container named in PG_CONTAINER_NAME (version-
 *     matched dump) and falling back to the host pg_dump binary on the CI
 *     freshness path. Grants are captured separately from information_schema
 *     because pg_dump --no-privileges strips them.
 *
 * The FTS5 virtual table in sqlite/connection.ts is NOT in scope — Drizzle
 * Kit cannot express FTS5, so it never appears in any migration. The
 * connection.ts file applies SCHEMA_SQL first, then the FTS5 block.
 */

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createClient } from "@libsql/client";
import postgres from "postgres";
import {
  runPgMigrations,
  runSqliteMigrations,
} from "../src/storage/migrate.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SERVER_ROOT = join(__dirname, "..");

const GENERATED_HEADER = `// Code generated by scripts/generate-schema-sql.ts; DO NOT EDIT.
//
// SCHEMA_SQL is the fresh-database bootstrap path. It runs every server
// boot via createConnection() and must stay in sync with the Drizzle
// migrations under drizzle/<dialect>/. To refresh, run:
//   pnpm --filter @mymehq/server schema-sql:generate
// (or implicitly via migrate:<dialect>:generate when a new migration lands).
//
// Hand-edits to this file will be overwritten on the next regen and will
// fail the schema-sql-freshness CI check.
`;

type Dialect = "pg" | "sqlite";

function parseDialect(): Dialect {
  const arg = process.argv.find((a) => a.startsWith("--dialect="));
  if (!arg) {
    throw new Error("--dialect=pg|sqlite is required");
  }
  const value = arg.split("=")[1] ?? "";
  if (value !== "pg" && value !== "sqlite") {
    throw new Error(`unknown dialect: ${value}`);
  }
  return value;
}

// ---------------------------------------------------------------------------
// SQLite
// ---------------------------------------------------------------------------

/**
 * Apply migrations to an in-memory libsql DB and dump the resulting schema.
 *
 * Order: tables first (in `rootpage` order, which is creation order), then
 * indexes grouped by table. `rootpage` is stable for a given migration set —
 * sqlite assigns it on table creation and never reuses it.
 */
async function dumpSqlite(): Promise<string> {
  // Use a shared-cache in-memory URL so the migrator and dump connection see
  // the same in-memory DB across libsql client logical connections. Matches
  // the URL shape `toLibsqlUrl(":memory:")` produces in sqlite/connection.ts.
  const url = "file::memory:?cache=shared";
  await runSqliteMigrations(url);

  const client = createClient({ url });
  try {
    const tables = await client.execute({
      sql: `
        SELECT name, sql
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
          AND name != '__drizzle_migrations'
        ORDER BY rootpage
      `,
      args: [],
    });
    const indexes = await client.execute({
      sql: `
        SELECT name, sql, tbl_name
        FROM sqlite_master
        WHERE type = 'index'
          AND sql IS NOT NULL
          AND tbl_name NOT LIKE 'sqlite_%'
          AND tbl_name != '__drizzle_migrations'
        ORDER BY tbl_name, name
      `,
      args: [],
    });

    const parts: string[] = [];
    for (const row of tables.rows) {
      parts.push(toIdempotentSqlite(row.sql as string) + ";");
    }
    for (const row of indexes.rows) {
      parts.push(toIdempotentSqlite(row.sql as string) + ";");
    }
    return parts.join("\n\n") + "\n";
  } finally {
    client.close();
  }
}

/**
 * Rewrite a SQLite DDL statement for re-run safety:
 *   CREATE TABLE          -> CREATE TABLE IF NOT EXISTS
 *   CREATE INDEX          -> CREATE INDEX IF NOT EXISTS
 *   CREATE UNIQUE INDEX   -> CREATE UNIQUE INDEX IF NOT EXISTS
 *
 * sqlite_master returns the original DDL as written in the migration, which
 * for Drizzle-generated migrations never includes IF NOT EXISTS — those
 * guards are added here so SCHEMA_SQL is idempotent across server boots.
 */
function toIdempotentSqlite(ddl: string): string {
  return ddl
    .replace(/^CREATE TABLE(?! IF NOT EXISTS)\b/i, "CREATE TABLE IF NOT EXISTS")
    .replace(
      /^CREATE UNIQUE INDEX(?! IF NOT EXISTS)\b/i,
      "CREATE UNIQUE INDEX IF NOT EXISTS",
    )
    .replace(
      /^CREATE INDEX(?! IF NOT EXISTS)\b/i,
      "CREATE INDEX IF NOT EXISTS",
    );
}

// ---------------------------------------------------------------------------
// Postgres
// ---------------------------------------------------------------------------

/**
 * Apply migrations against the DATABASE_URL container, capture the dump via
 * pg_dump (container-side when possible for version-matched output), then
 * post-process for re-run safety and write.
 */
async function dumpPg(): Promise<string> {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error(
      "DATABASE_URL is required for --dialect=pg. Run via " +
        "`bash packages/server/scripts/with-temp-pg.sh ...` or set the env var directly.",
    );
  }

  await runPgMigrations(databaseUrl);

  // Grants on the myme_app role — captured before pg_dump strips them.
  // pg_dump --no-privileges discards GRANT statements; reinstated below
  // from information_schema.
  const grants = await fetchPgGrants(databaseUrl);
  const dump = invokePgDump(databaseUrl);

  // Tripwire — fail loud if a future migration adds object types this
  // generator hasn't been audited for. Today: zero hits across drizzle/pg/.
  assertNoUnsupportedObjectTypes(dump);

  const processed = postProcessPgDump(dump);
  const { role: roleBlock, grants: grantsBlock } = buildPgRoleAndGrants(grants);

  // Order matters at apply time:
  //   1. Role (DO IF NOT EXISTS) — RLS policies later reference `myme_app`.
  //   2. pg_dump output — tables, indexes, constraints, IDENTITY, RLS enable,
  //      policies. Policies reference the role; the role now exists.
  //   3. Grants — applied to tables that now exist. Grants don't gate policy
  //      creation, so emitting them last is safe.
  return roleBlock + "\n" + processed + "\n" + grantsBlock;
}

/**
 * Invoke pg_dump. Prefer container-side via `docker exec` when
 * PG_CONTAINER_NAME is set (version-matched dump, no host binary required).
 * Otherwise fall back to the host pg_dump — used on the CI freshness path
 * where the runner reaches the postgres service container directly.
 */
function invokePgDump(databaseUrl: string): string {
  const dumpArgs = [
    "--schema-only",
    "--no-owner",
    "--no-privileges",
    "--no-comments",
    "--schema=public",
    "--exclude-schema=drizzle",
  ];
  const container = process.env.PG_CONTAINER_NAME;
  let result;
  if (container) {
    // Container-side: rebuild the URL with localhost:5432 since the dumper
    // sees Postgres on its native port inside the container, not the
    // host-mapped one.
    const innerUrl = databaseUrl.replace(/@[^/]+\//, "@localhost:5432/");
    result = spawnSync(
      "docker",
      ["exec", container, "pg_dump", ...dumpArgs, innerUrl],
      { encoding: "utf-8", maxBuffer: 32 * 1024 * 1024 },
    );
  } else {
    result = spawnSync("pg_dump", [...dumpArgs, databaseUrl], {
      encoding: "utf-8",
      maxBuffer: 32 * 1024 * 1024,
    });
  }
  if (result.status !== 0) {
    const stderr: string =
      typeof result.stderr === "string" ? result.stderr : "no stderr";
    const status: string =
      result.status == null ? "null" : String(result.status);
    throw new Error(`pg_dump failed (exit ${status}): ${stderr}`);
  }
  return typeof result.stdout === "string" ? result.stdout : "";
}

interface PgGrant {
  table_name: string;
  privilege_type: string;
}

async function fetchPgGrants(databaseUrl: string): Promise<PgGrant[]> {
  const sql = postgres(databaseUrl, { max: 1 });
  try {
    const rows = await sql<PgGrant[]>`
      SELECT table_name, privilege_type
      FROM information_schema.role_table_grants
      WHERE grantee = 'myme_app'
        AND table_schema = 'public'
      ORDER BY table_name, privilege_type
    `;
    return [...rows];
  } finally {
    await sql.end();
  }
}

/**
 * Reconstruct the role + grants blocks that pg_dump --no-privileges strips.
 *
 * Returned as two separate strings so the caller can emit them at the right
 * apply-time points:
 *   - `role`   — emitted BEFORE the pg_dump body; policies reference the role.
 *   - `grants` — emitted AFTER the pg_dump body; tables must exist first.
 *
 * Tables with identical privilege sets share a single GRANT line — matches
 * the shape of the prior hand-written SCHEMA_SQL closely enough that
 * reviewers can audit grants visually. Stable ordering (verb-set key, then
 * alphabetical table) guarantees deterministic output for the freshness
 * diff.
 */
function buildPgRoleAndGrants(grants: PgGrant[]): {
  role: string;
  grants: string;
} {
  const verbsByTable = new Map<string, Set<string>>();
  for (const g of grants) {
    let set = verbsByTable.get(g.table_name);
    if (!set) {
      set = new Set();
      verbsByTable.set(g.table_name, set);
    }
    set.add(g.privilege_type);
  }

  const tablesByVerbSet = new Map<string, string[]>();
  for (const [table, verbs] of verbsByTable) {
    const key = [...verbs].sort().join(",");
    let bucket = tablesByVerbSet.get(key);
    if (!bucket) {
      bucket = [];
      tablesByVerbSet.set(key, bucket);
    }
    bucket.push(table);
  }

  const roleLines: string[] = [
    "-- T-145: SCHEMA_SQL is auto-generated. The myme_app role + grants are",
    "-- reconstructed from information_schema because pg_dump --no-privileges",
    "-- strips them. The role is emitted first (RLS policies reference it);",
    "-- table grants are emitted after the pg_dump body (tables must exist).",
    "DO $$",
    "BEGIN",
    `  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'myme_app') THEN`,
    `    CREATE ROLE "myme_app";`,
    "  END IF;",
    "END",
    "$$;",
    `GRANT USAGE ON SCHEMA public TO "myme_app";`,
  ];

  const grantLines: string[] = [
    "-- Table grants on the myme_app role (T-145; see role block above).",
    "-- Schema-qualified (`public.x`) so the grants resolve regardless of",
    "-- search_path — pg_dump emits its CREATE TABLE statements with the",
    "-- `public.` prefix, and grants must match the qualified table for",
    "-- non-default search_paths (e.g. test schemas) to apply correctly.",
  ];
  const sortedKeys = [...tablesByVerbSet.keys()].sort();
  for (const key of sortedKeys) {
    const verbs = key.split(",").join(", ");
    const bucket = tablesByVerbSet.get(key) ?? [];
    const tables = [...bucket]
      .sort()
      .map((t) => `"public"."${t}"`)
      .join(", ");
    grantLines.push(`GRANT ${verbs} ON ${tables} TO "myme_app";`);
  }

  // Sequence usage — myme_app needs to insert into IDENTITY columns
  // (event_log.id). Granted blanket; matches the prior SCHEMA_SQL.
  grantLines.push(
    `GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "myme_app";`,
  );

  return {
    role: roleLines.join("\n") + "\n",
    grants: grantLines.join("\n") + "\n",
  };
}

const UNSUPPORTED_OBJECT_PATTERNS: readonly (readonly [RegExp, string])[] = [
  [/^CREATE EXTENSION\b/im, "CREATE EXTENSION"],
  [/^CREATE (OR REPLACE )?FUNCTION\b/im, "CREATE FUNCTION"],
  [/^CREATE (OR REPLACE )?VIEW\b/im, "CREATE VIEW"],
  [/^CREATE (OR REPLACE )?TRIGGER\b/im, "CREATE TRIGGER"],
  [/^CREATE MATERIALIZED VIEW\b/im, "CREATE MATERIALIZED VIEW"],
  [/^CREATE (OR REPLACE )?PROCEDURE\b/im, "CREATE PROCEDURE"],
  [/^CREATE DOMAIN\b/im, "CREATE DOMAIN"],
  [/^CREATE TYPE\b/im, "CREATE TYPE"],
];

function assertNoUnsupportedObjectTypes(dump: string): void {
  const hits: string[] = [];
  for (const [pattern, name] of UNSUPPORTED_OBJECT_PATTERNS) {
    if (pattern.test(dump)) hits.push(name);
  }
  if (hits.length > 0) {
    throw new Error(
      `Unsupported PG object type(s) in dump: ${hits.join(", ")}.\n` +
        `generate-schema-sql.ts only handles tables, indexes, RLS policies, ` +
        `and identity sequences. Extend the generator before adding a ` +
        `migration that uses these object types, or SCHEMA_SQL will diverge ` +
        `from the migrations.`,
    );
  }
}

/**
 * Post-process pg_dump output for re-run safety inside the bootstrap path:
 *  - Strip SET statements, pg_catalog.set_config calls, and `\restrict` /
 *    `\unrestrict` psql backslash commands (PG 17.5+ dump-encryption noise).
 *  - Strip pg_dump header comments.
 *  - `CREATE SCHEMA public` → `CREATE SCHEMA IF NOT EXISTS public`.
 *  - `CREATE TABLE` / `CREATE INDEX` / `CREATE UNIQUE INDEX` → IF NOT EXISTS.
 *  - `CREATE POLICY x ON t ...` → `DROP POLICY IF EXISTS x ON t; CREATE POLICY ...`.
 *  - `ALTER TABLE ... ADD CONSTRAINT c ...` →
 *        `ALTER TABLE ... DROP CONSTRAINT IF EXISTS c;` + the original ADD.
 *  - `ALTER TABLE ... ALTER COLUMN c ADD GENERATED ...` →
 *        `ALTER TABLE ... ALTER COLUMN c DROP IDENTITY IF EXISTS;` + original.
 *
 * ALTER TABLE ... ENABLE ROW LEVEL SECURITY is naturally idempotent.
 *
 * All of these are safe because SCHEMA_SQL runs inside pg_advisory_lock(42),
 * which serializes server startups — there are no concurrent writers during
 * the brief window between DROP and re-CREATE.
 */
function postProcessPgDump(dump: string): string {
  const out: string[] = [];
  const lines = dump.split("\n");
  let buffer: string[] = [];
  const flush = (): void => {
    if (buffer.length === 0) return;
    const stmt = buffer.join("\n").trim();
    buffer = [];
    if (stmt === "") return;
    out.push(transformPgStatement(stmt));
  };
  for (const line of lines) {
    if (line.startsWith("--") && buffer.length === 0) continue;
    if (/^\s*SET\s/i.test(line) && buffer.length === 0) continue;
    if (/^\s*SELECT pg_catalog\.set_config/i.test(line) && buffer.length === 0)
      continue;
    // PG 17.5+ wraps dumps with psql `\restrict <key>` / `\unrestrict <key>`
    // backslash commands to bind the dump to a pg_restore invocation. These
    // aren't SQL — they're psql-only — and would fail when fed to a libsql /
    // postgres-js client. Strip.
    if (/^\s*\\(restrict|unrestrict)\b/i.test(line)) continue;
    if (line.trim() === "" && buffer.length === 0) continue;
    buffer.push(line);
    if (line.trimEnd().endsWith(";")) {
      flush();
    }
  }
  flush();
  return out.filter((s) => s.trim() !== "").join("\n\n") + "\n";
}

function transformPgStatement(stmt: string): string {
  let out = stmt
    .replace(/^CREATE TABLE(?! IF NOT EXISTS)\b/i, "CREATE TABLE IF NOT EXISTS")
    .replace(
      /^CREATE UNIQUE INDEX(?! IF NOT EXISTS)\b/i,
      "CREATE UNIQUE INDEX IF NOT EXISTS",
    )
    .replace(/^CREATE INDEX(?! IF NOT EXISTS)\b/i, "CREATE INDEX IF NOT EXISTS")
    .replace(
      /^CREATE SCHEMA(?! IF NOT EXISTS)\b/i,
      "CREATE SCHEMA IF NOT EXISTS",
    );

  const policyMatch = /^CREATE POLICY ("?[^"\s]+"?) ON ("?[^"\s]+"?)/i.exec(
    out,
  );
  if (policyMatch) {
    const name = policyMatch[1] ?? "";
    const table = policyMatch[2] ?? "";
    out = `DROP POLICY IF EXISTS ${name} ON ${table};\n${out}`;
  }

  // ALTER TABLE [ONLY] <table> ... ADD CONSTRAINT <name> ...
  // Cannot use DROP CONSTRAINT IF EXISTS + ADD here: FKs depend on PKs /
  // UNIQUEs, so dropping a PK cascades. Wrap in DO IF NOT EXISTS instead —
  // re-runs simply skip when the constraint already exists.
  const addConstraintMatch =
    /^ALTER TABLE (ONLY )?("?[\w.]+"?(?:\.[\w"]+)?)\s+ADD CONSTRAINT (\w+)/im.exec(
      out,
    );
  if (addConstraintMatch) {
    const tableRef = addConstraintMatch[2] ?? "";
    const conName = addConstraintMatch[3] ?? "";
    out = wrapInDoIfNotExists(
      `SELECT 1 FROM pg_constraint WHERE conname = '${conName}' AND conrelid = '${tableRef}'::regclass`,
      out,
    );
  }

  // ALTER TABLE <table> ALTER COLUMN <col> ADD GENERATED ...
  // Same shape — DROP IDENTITY IF EXISTS would work standalone (no cascade)
  // but we keep the pattern uniform with ADD CONSTRAINT for reviewability.
  const addIdentityMatch =
    /^ALTER TABLE ("?[\w.]+"?)\s+ALTER COLUMN (\w+) ADD GENERATED/im.exec(out);
  if (addIdentityMatch) {
    const tableRef = addIdentityMatch[1] ?? "";
    const col = addIdentityMatch[2] ?? "";
    out = wrapInDoIfNotExists(
      `SELECT 1 FROM pg_attribute WHERE attrelid = '${tableRef}'::regclass AND attname = '${col}' AND attidentity != ''`,
      out,
    );
  }

  return out;
}

function wrapInDoIfNotExists(existsQuery: string, stmt: string): string {
  // Strip trailing `;` from inner stmt — the DO block ends with its own `;`.
  const inner = stmt.replace(/;\s*$/, "");
  return [
    "DO $$",
    "BEGIN",
    `  IF NOT EXISTS (${existsQuery}) THEN`,
    `    ${inner.split("\n").join("\n    ")};`,
    "  END IF;",
    "END",
    "$$;",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Output
// ---------------------------------------------------------------------------

function writeGenerated(dialect: Dialect, sql: string): string {
  const outPath = join(
    SERVER_ROOT,
    "src",
    "storage",
    dialect,
    "schema-sql.generated.ts",
  );
  mkdirSync(dirname(outPath), { recursive: true });
  // Escape for embedding into a template literal.
  const escaped = sql
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  const body = `${GENERATED_HEADER}
export const SCHEMA_SQL = \`
${escaped}\`;
`;
  writeFileSync(outPath, body, "utf-8");
  return outPath;
}

async function main(): Promise<void> {
  const dialect = parseDialect();
  process.stderr.write(`Generating ${dialect} SCHEMA_SQL...\n`);
  const sql = dialect === "sqlite" ? await dumpSqlite() : await dumpPg();
  const outPath = writeGenerated(dialect, sql);
  process.stderr.write(`  → ${outPath}\n`);
}

main().then(
  () => process.exit(0),
  (err: unknown) => {
    process.stderr.write(`generate-schema-sql failed: ${String(err)}\n`);
    process.exit(1);
  },
);
