/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminRemovePlatformType200Response {
    #[serde(rename = "removed")]
    pub removed: Removed,
    #[serde(rename = "id")]
    pub id: String,
}

impl AdminRemovePlatformType200Response {
    pub fn new(removed: Removed, id: String) -> AdminRemovePlatformType200Response {
        AdminRemovePlatformType200Response { removed, id }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Removed {
    #[serde(rename = "true")]
    True,
}

impl Default for Removed {
    fn default() -> Removed {
        Self::True
    }
}
