/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlobOrphanPage {
    #[serde(rename = "data")]
    pub data: Vec<models::BlobOrphan>,
    /// Pass as `cursor` for the next page; `null` on the last. A page can be short, or empty, with a cursor still to follow, so a walk stops on `null` and never on a short page.
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
}

impl BlobOrphanPage {
    pub fn new(data: Vec<models::BlobOrphan>, next_cursor: Option<String>) -> BlobOrphanPage {
        BlobOrphanPage { data, next_cursor }
    }
}
