/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlobNotFoundRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::BlobNotFoundRefusalError>,
}

impl BlobNotFoundRefusal {
    pub fn new(error: models::BlobNotFoundRefusalError) -> BlobNotFoundRefusal {
        BlobNotFoundRefusal {
            error: Box::new(error),
        }
    }
}
