/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlobStore {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "locator")]
    pub locator: String,
    #[serde(rename = "policy")]
    pub policy: String,
    #[serde(rename = "attached_at")]
    pub attached_at: String,
    #[serde(rename = "detached_at", deserialize_with = "Option::deserialize")]
    pub detached_at: Option<String>,
}

impl BlobStore {
    pub fn new(
        id: String,
        kind: Kind,
        locator: String,
        policy: String,
        attached_at: String,
        detached_at: Option<String>,
    ) -> BlobStore {
        BlobStore {
            id,
            kind,
            locator,
            policy,
            attached_at,
            detached_at,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "disk")]
    Disk,
    #[serde(rename = "s3")]
    S3,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Disk
    }
}
