/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlobOrphan {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "size_bytes")]
    pub size_bytes: i32,
    #[serde(rename = "reported_at")]
    pub reported_at: String,
}

impl BlobOrphan {
    pub fn new(
        hash: String,
        mime_type: String,
        size_bytes: i32,
        reported_at: String,
    ) -> BlobOrphan {
        BlobOrphan {
            hash,
            mime_type,
            size_bytes,
            reported_at,
        }
    }
}
