/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkAtomicRollbackOrMissingRequiredFieldOrValidationErrorRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::BulkAtomicRollbackOrMissingRequiredFieldOrValidationErrorRefusalError>,
}

impl BulkAtomicRollbackOrMissingRequiredFieldOrValidationErrorRefusal {
    pub fn new(
        error: models::BulkAtomicRollbackOrMissingRequiredFieldOrValidationErrorRefusalError,
    ) -> BulkAtomicRollbackOrMissingRequiredFieldOrValidationErrorRefusal {
        BulkAtomicRollbackOrMissingRequiredFieldOrValidationErrorRefusal {
            error: Box::new(error),
        }
    }
}
