/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpsertItemsRequest {
    #[serde(rename = "items")]
    pub items: Vec<models::BulkUpsertItemsRequestItemsInner>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<Mode>,
    #[serde(rename = "atomic", skip_serializing_if = "Option::is_none")]
    pub atomic: Option<bool>,
    #[serde(rename = "enable_fanout", skip_serializing_if = "Option::is_none")]
    pub enable_fanout: Option<bool>,
    #[serde(rename = "retype", skip_serializing_if = "Option::is_none")]
    pub retype: Option<bool>,
}

impl BulkUpsertItemsRequest {
    pub fn new(items: Vec<models::BulkUpsertItemsRequestItemsInner>) -> BulkUpsertItemsRequest {
        BulkUpsertItemsRequest {
            items,
            mode: None,
            atomic: None,
            enable_fanout: None,
            retype: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "upsert")]
    Upsert,
    #[serde(rename = "create_only")]
    CreateOnly,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Upsert
    }
}
