/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkAtomicRollbackOrForbiddenOrTypeNotPermittedRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::BulkAtomicRollbackOrForbiddenOrTypeNotPermittedRefusalError>,
}

impl BulkAtomicRollbackOrForbiddenOrTypeNotPermittedRefusal {
    pub fn new(
        error: models::BulkAtomicRollbackOrForbiddenOrTypeNotPermittedRefusalError,
    ) -> BulkAtomicRollbackOrForbiddenOrTypeNotPermittedRefusal {
        BulkAtomicRollbackOrForbiddenOrTypeNotPermittedRefusal {
            error: Box::new(error),
        }
    }
}
