/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkActionJob {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "status")]
    pub status: models::BulkActionJobStatus,
    #[serde(rename = "matched")]
    pub matched: i32,
    #[serde(rename = "processed")]
    pub processed: i32,
    #[serde(rename = "succeeded")]
    pub succeeded: i32,
    #[serde(rename = "errored")]
    pub errored: i32,
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    #[serde(rename = "finished_at", skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<Box<models::BulkActionResult>>,
}

impl BulkActionJob {
    pub fn new(
        id: String,
        action: String,
        status: models::BulkActionJobStatus,
        matched: i32,
        processed: i32,
        succeeded: i32,
        errored: i32,
    ) -> BulkActionJob {
        BulkActionJob {
            id,
            action,
            status,
            matched,
            processed,
            succeeded,
            errored,
            started_at: None,
            finished_at: None,
            error: None,
            result: None,
        }
    }
}
