/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkGetItems200Response {
    /// The items the caller may read, in the order `ids` named them, an id named twice answered once. Ids that do not resolve, or name a trashed item or one whose type the caller may not read, are left out.
    #[serde(rename = "items")]
    pub items: Vec<models::Item>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Vec<models::Metadata>>,
}

impl BulkGetItems200Response {
    pub fn new(items: Vec<models::Item>) -> BulkGetItems200Response {
        BulkGetItems200Response {
            items,
            metadata: None,
        }
    }
}
