/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpsertEdgesRequestEdgesInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "source_id")]
    pub source_id: String,
    #[serde(rename = "target_id")]
    pub target_id: String,
    #[serde(rename = "edge_type")]
    pub edge_type: String,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The version the caller read, where this entry resolves an edge that already exists. A stale value is refused as that entry's outcome, or rolls the page back under the default `atomic`.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
}

impl BulkUpsertEdgesRequestEdgesInner {
    pub fn new(
        source_id: String,
        target_id: String,
        edge_type: String,
    ) -> BulkUpsertEdgesRequestEdgesInner {
        BulkUpsertEdgesRequestEdgesInner {
            id: None,
            source_id,
            target_id,
            edge_type,
            properties: None,
            version: None,
        }
    }
}
