/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConflictOrLinkTakenRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::ConflictOrLinkTakenRefusalError>,
}

impl ConflictOrLinkTakenRefusal {
    pub fn new(error: models::ConflictOrLinkTakenRefusalError) -> ConflictOrLinkTakenRefusal {
        ConflictOrLinkTakenRefusal {
            error: Box::new(error),
        }
    }
}
