/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConflictSnapshot {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "properties")]
    pub properties: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "tier")]
    pub tier: models::Tier,
    #[serde(rename = "occurred_at")]
    pub occurred_at: String,
    #[serde(rename = "source_id", deserialize_with = "Option::deserialize")]
    pub source_id: Option<String>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ConflictSnapshot {
    pub fn new(
        id: String,
        version: f64,
        properties: std::collections::HashMap<String, serde_json::Value>,
        tier: models::Tier,
        occurred_at: String,
        source_id: Option<String>,
        r#type: String,
    ) -> ConflictSnapshot {
        ConflictSnapshot {
            id,
            version,
            properties,
            tier,
            occurred_at,
            source_id,
            r#type,
        }
    }
}
