/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Connector {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "key_id")]
    pub key_id: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", deserialize_with = "Option::deserialize")]
    pub description: Option<String>,
    #[serde(rename = "registered_at")]
    pub registered_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "last_heartbeat_at", deserialize_with = "Option::deserialize")]
    pub last_heartbeat_at: Option<String>,
    #[serde(rename = "last_run", deserialize_with = "Option::deserialize")]
    pub last_run: Option<Box<models::ConnectorRun>>,
    /// When the hold a process took at `POST /connectors/{id}/hold` lapses; `null` when no process holds the registration or its hold has lapsed.
    #[serde(rename = "hold_expires_at", deserialize_with = "Option::deserialize")]
    pub hold_expires_at: Option<String>,
}

impl Connector {
    pub fn new(
        id: String,
        key_id: String,
        source: String,
        name: String,
        description: Option<String>,
        registered_at: String,
        updated_at: String,
        last_heartbeat_at: Option<String>,
        last_run: Option<models::ConnectorRun>,
        hold_expires_at: Option<String>,
    ) -> Connector {
        Connector {
            id,
            key_id,
            source,
            name,
            description,
            registered_at,
            updated_at,
            last_heartbeat_at,
            last_run: if let Some(x) = last_run {
                Some(Box::new(x))
            } else {
                None
            },
            hold_expires_at,
        }
    }
}
