/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectorHeldRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::ConnectorHeldRefusalError>,
}

impl ConnectorHeldRefusal {
    pub fn new(error: models::ConnectorHeldRefusalError) -> ConnectorHeldRefusal {
        ConnectorHeldRefusal {
            error: Box::new(error),
        }
    }
}
