/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoreTypeImmutableOrForbiddenOrTypeNotPermittedRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::CoreTypeImmutableOrForbiddenOrTypeNotPermittedRefusalError>,
}

impl CoreTypeImmutableOrForbiddenOrTypeNotPermittedRefusal {
    pub fn new(
        error: models::CoreTypeImmutableOrForbiddenOrTypeNotPermittedRefusalError,
    ) -> CoreTypeImmutableOrForbiddenOrTypeNotPermittedRefusal {
        CoreTypeImmutableOrForbiddenOrTypeNotPermittedRefusal {
            error: Box::new(error),
        }
    }
}
