/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoreTypeImmutableOrForbiddenRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::CoreTypeImmutableOrForbiddenRefusalError>,
}

impl CoreTypeImmutableOrForbiddenRefusal {
    pub fn new(
        error: models::CoreTypeImmutableOrForbiddenRefusalError,
    ) -> CoreTypeImmutableOrForbiddenRefusal {
        CoreTypeImmutableOrForbiddenRefusal {
            error: Box::new(error),
        }
    }
}
