/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateInboundEndpointRequest {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// A header whose value names a delivery, such as `X-GitHub-Delivery`: a delivery repeating a value is marked as a repeat, never dropped.
    #[serde(rename = "duplicate_header", skip_serializing_if = "Option::is_none")]
    pub duplicate_header: Option<String>,
}

impl CreateInboundEndpointRequest {
    pub fn new() -> CreateInboundEndpointRequest {
        CreateInboundEndpointRequest {
            label: None,
            duplicate_header: None,
        }
    }
}
