/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWebhookRequest {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "events")]
    pub events: Vec<Events>,
    #[serde(
        rename = "type_filter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub type_filter: Option<Option<String>>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl CreateWebhookRequest {
    pub fn new(url: String, events: Vec<Events>) -> CreateWebhookRequest {
        CreateWebhookRequest {
            url,
            events,
            type_filter: None,
            secret: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "item.created")]
    ItemCreated,
    #[serde(rename = "item.updated")]
    ItemUpdated,
    #[serde(rename = "item.deleted")]
    ItemDeleted,
    #[serde(rename = "item.restored")]
    ItemRestored,
    #[serde(rename = "item.purged")]
    ItemPurged,
    #[serde(rename = "item.state_changed")]
    ItemStateChanged,
    #[serde(rename = "metadata.changed")]
    MetadataChanged,
    #[serde(rename = "edge.created")]
    EdgeCreated,
    #[serde(rename = "edge.updated")]
    EdgeUpdated,
    #[serde(rename = "edge.deleted")]
    EdgeDeleted,
}

impl Default for Events {
    fn default() -> Events {
        Self::ItemCreated
    }
}
