/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEdgeType201Response {
    #[serde(rename = "edge_type")]
    pub edge_type: Box<models::EdgeType>,
}

impl CreateEdgeType201Response {
    pub fn new(edge_type: models::EdgeType) -> CreateEdgeType201Response {
        CreateEdgeType201Response {
            edge_type: Box::new(edge_type),
        }
    }
}
