/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateKeyRequest {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "source")]
    pub source: String,
    /// The sources a write by this key may name besides its own `source`, so its rows are keyed by the named source. Two keys may claim one source, which is how two devices present one natural key; a key's own `source` stays unique. Held to the rules the permission maps keep: omitted on a create that names no map either, it takes the creator's claims; named, it is only what it names; a working key may grant only its own `source` and what it claims itself, and the operator key may grant any. A source starting `oauth:` or `connector:` is refused.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<String>>,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Vec<models::Permission>>,
    #[serde(rename = "default_tier", skip_serializing_if = "Option::is_none")]
    pub default_tier: Option<models::Tier>,
    #[serde(rename = "is_operator", skip_serializing_if = "Option::is_none")]
    pub is_operator: Option<bool>,
    #[serde(rename = "type_permissions", skip_serializing_if = "Option::is_none")]
    pub type_permissions: Option<std::collections::HashMap<String, models::TypePermissionLevel>>,
    #[serde(
        rename = "extension_permissions",
        skip_serializing_if = "Option::is_none"
    )]
    pub extension_permissions: Option<std::collections::HashMap<String, models::PermissionLevel>>,
    #[serde(rename = "edge_permissions", skip_serializing_if = "Option::is_none")]
    pub edge_permissions: Option<std::collections::HashMap<String, models::PermissionLevel>>,
    #[serde(
        rename = "metadata_permissions",
        skip_serializing_if = "Option::is_none"
    )]
    pub metadata_permissions: Option<std::collections::HashMap<String, models::PermissionLevel>>,
    #[serde(
        rename = "profile_permissions",
        skip_serializing_if = "Option::is_none"
    )]
    pub profile_permissions: Option<std::collections::HashMap<String, models::PermissionLevel>>,
    #[serde(
        rename = "enforcement_override",
        skip_serializing_if = "Option::is_none"
    )]
    pub enforcement_override: Option<Box<models::EnforcementOverride>>,
}

impl CreateKeyRequest {
    pub fn new(label: String, source: String) -> CreateKeyRequest {
        CreateKeyRequest {
            label,
            source,
            sources: None,
            permissions: None,
            default_tier: None,
            is_operator: None,
            type_permissions: None,
            extension_permissions: None,
            edge_permissions: None,
            metadata_permissions: None,
            profile_permissions: None,
            enforcement_override: None,
        }
    }
}
