/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateItemRequest {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "occurred_at", skip_serializing_if = "Option::is_none")]
    pub occurred_at: Option<String>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(rename = "source_id", skip_serializing_if = "Option::is_none")]
    pub source_id: Option<String>,
    /// Optional, and meaningful on one path: a `source_id` resolving a live row makes this write an upsert, and a version here makes that upsert conditional exactly as it is on the update door. Everywhere else it is ignored, because nothing is overwritten — a genuine create has no version to have read, and a repeated `id` or a natural key resolving a trashed row is acknowledged rather than written.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<models::Tier>,
    #[serde(rename = "capture_latitude", skip_serializing_if = "Option::is_none")]
    pub capture_latitude: Option<f64>,
    #[serde(rename = "capture_longitude", skip_serializing_if = "Option::is_none")]
    pub capture_longitude: Option<f64>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "edges", skip_serializing_if = "Option::is_none")]
    pub edges: Option<std::collections::HashMap<String, Vec<String>>>,
}

impl CreateItemRequest {
    pub fn new(r#type: String) -> CreateItemRequest {
        CreateItemRequest {
            r#type,
            properties: None,
            id: None,
            state: None,
            occurred_at: None,
            source: None,
            source_id: None,
            version: None,
            tier: None,
            capture_latitude: None,
            capture_longitude: None,
            tags: None,
            edges: None,
        }
    }
}
