/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdgeTypePage {
    #[serde(rename = "data")]
    pub data: Vec<models::EdgeType>,
    /// Pass as `cursor` for the next page; `null` on the last. A page can be short, or empty, with a cursor still to follow, so a walk stops on `null` and never on a short page.
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
}

impl EdgeTypePage {
    pub fn new(data: Vec<models::EdgeType>, next_cursor: Option<String>) -> EdgeTypePage {
        EdgeTypePage { data, next_cursor }
    }
}
