/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdgeTypeRequestPropertySchemaValue {
    /// A field type's name, stored as given rather than checked against the ones a type's `fields` take, and never `thumbnail`: an edge carries no thumbnail.
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "enum_values", skip_serializing_if = "Option::is_none")]
    pub enum_values: Option<Vec<String>>,
    /// A field type's name, stored as given rather than checked against the ones a type's `fields` take, and never `thumbnail`: an edge carries no thumbnail.
    #[serde(rename = "items_type", skip_serializing_if = "Option::is_none")]
    pub items_type: Option<String>,
    /// A refinement of a string property, stored as given, and never `thumbnail`: an edge carries no thumbnail.
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
}

impl EdgeTypeRequestPropertySchemaValue {
    pub fn new(r#type: String) -> EdgeTypeRequestPropertySchemaValue {
        EdgeTypeRequestPropertySchemaValue {
            r#type,
            description: None,
            required: None,
            enum_values: None,
            items_type: None,
            format: None,
        }
    }
}
