/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdgeConstraintViolationOrEdgeCycleOrInvalidIdOrInvalidPropertiesOrMissingRequiredFieldOrUnknownTypeOrValidationErrorRefusalError
{
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl EdgeConstraintViolationOrEdgeCycleOrInvalidIdOrInvalidPropertiesOrMissingRequiredFieldOrUnknownTypeOrValidationErrorRefusalError {
    pub fn new(code: Code, message: String) -> EdgeConstraintViolationOrEdgeCycleOrInvalidIdOrInvalidPropertiesOrMissingRequiredFieldOrUnknownTypeOrValidationErrorRefusalError {
        EdgeConstraintViolationOrEdgeCycleOrInvalidIdOrInvalidPropertiesOrMissingRequiredFieldOrUnknownTypeOrValidationErrorRefusalError {
            code,
            message,
            details: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "edge_constraint_violation")]
    EdgeConstraintViolation,
    #[serde(rename = "edge_cycle")]
    EdgeCycle,
    #[serde(rename = "invalid_id")]
    InvalidId,
    #[serde(rename = "invalid_properties")]
    InvalidProperties,
    #[serde(rename = "missing_required_field")]
    MissingRequiredField,
    #[serde(rename = "unknown_type")]
    UnknownType,
    #[serde(rename = "validation_error")]
    ValidationError,
}

impl Default for Code {
    fn default() -> Code {
        Self::EdgeConstraintViolation
    }
}
