/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindConnectorAgreements200Response {
    #[serde(rename = "data")]
    pub data: Vec<models::ConnectorAgreement>,
}

impl FindConnectorAgreements200Response {
    pub fn new(data: Vec<models::ConnectorAgreement>) -> FindConnectorAgreements200Response {
        FindConnectorAgreements200Response { data }
    }
}
