/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HousekeepingOutcome {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "error")]
    Error,
}

impl std::fmt::Display for HousekeepingOutcome {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ok => write!(f, "ok"),
            Self::Error => write!(f, "error"),
        }
    }
}

impl Default for HousekeepingOutcome {
    fn default() -> HousekeepingOutcome {
        Self::Ok
    }
}
