/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdempotencyKeyInFlightRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::IdempotencyKeyInFlightRefusalError>,
}

impl IdempotencyKeyInFlightRefusal {
    pub fn new(error: models::IdempotencyKeyInFlightRefusalError) -> IdempotencyKeyInFlightRefusal {
        IdempotencyKeyInFlightRefusal {
            error: Box::new(error),
        }
    }
}
