/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundDeliveryDuplicateOf {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "outcome", deserialize_with = "Option::deserialize")]
    pub outcome: Option<Outcome>,
}

impl InboundDeliveryDuplicateOf {
    pub fn new(id: String, outcome: Option<Outcome>) -> InboundDeliveryDuplicateOf {
        InboundDeliveryDuplicateOf { id, outcome }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Outcome {
    #[serde(rename = "processed")]
    Processed,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "rejected")]
    Rejected,
}

impl Default for Outcome {
    fn default() -> Outcome {
        Self::Processed
    }
}
