/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceConfigEnforcement {
    #[serde(rename = "strict_mode", skip_serializing_if = "Option::is_none")]
    pub strict_mode: Option<Box<models::TypeLever>>,
    #[serde(rename = "source_allowlist", skip_serializing_if = "Option::is_none")]
    pub source_allowlist: Option<Box<models::TypeAndSourceLever>>,
    #[serde(rename = "source_filter", skip_serializing_if = "Option::is_none")]
    pub source_filter: Option<Box<models::TypeAndSourceLever>>,
}

impl InstanceConfigEnforcement {
    pub fn new() -> InstanceConfigEnforcement {
        InstanceConfigEnforcement {
            strict_mode: None,
            source_allowlist: None,
            source_filter: None,
        }
    }
}
