/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidIdOrValidationErrorRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::InvalidIdOrValidationErrorRefusalError>,
}

impl InvalidIdOrValidationErrorRefusal {
    pub fn new(
        error: models::InvalidIdOrValidationErrorRefusalError,
    ) -> InvalidIdOrValidationErrorRefusal {
        InvalidIdOrValidationErrorRefusal {
            error: Box::new(error),
        }
    }
}
