/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemStaleVersion {
    #[serde(rename = "error")]
    pub error: Box<models::VersionConflictError>,
    #[serde(rename = "current")]
    pub current: Box<models::ConflictSnapshot>,
}

impl ItemStaleVersion {
    pub fn new(
        error: models::VersionConflictError,
        current: models::ConflictSnapshot,
    ) -> ItemStaleVersion {
        ItemStaleVersion {
            error: Box::new(error),
            current: Box::new(current),
        }
    }
}
