/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupItemsRequest {
    /// The type the links are held in and the tombstones are kept under.
    #[serde(rename = "type")]
    pub r#type: String,
    /// Link values, which `type` must name a `link_field` for.
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<String>>,
    /// The source the `source_ids` are natural keys under.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Natural-key identifiers under `source`.
    #[serde(rename = "source_ids", skip_serializing_if = "Option::is_none")]
    pub source_ids: Option<Vec<String>>,
    /// Item ids.
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<String>>,
    /// `edges` hydrates each row's outbound edges as `GET /items?include=edges` does, held to the same two read permissions.
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<Include>>,
}

impl LookupItemsRequest {
    pub fn new(r#type: String) -> LookupItemsRequest {
        LookupItemsRequest {
            r#type,
            links: None,
            source: None,
            source_ids: None,
            ids: None,
            include: None,
        }
    }
}
/// `edges` hydrates each row's outbound edges as `GET /items?include=edges` does, held to the same two read permissions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Include {
    #[serde(rename = "edges")]
    Edges,
}

impl Default for Include {
    fn default() -> Include {
        Self::Edges
    }
}
