/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MergeStrategy {
    #[serde(rename = "last_writer_wins")]
    LastWriterWins,
    #[serde(rename = "keep_both_copies")]
    KeepBothCopies,
}

impl std::fmt::Display for MergeStrategy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LastWriterWins => write!(f, "last_writer_wins"),
            Self::KeepBothCopies => write!(f, "keep_both_copies"),
        }
    }
}

impl Default for MergeStrategy {
    fn default() -> MergeStrategy {
        Self::LastWriterWins
    }
}
