/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OccurrencePage {
    #[serde(rename = "data")]
    pub data: Vec<models::Occurrence>,
    /// Pass as `cursor` for the next page; `null` on the last. A page can be short, or empty, with a cursor still to follow, so a walk stops on `null` and never on a short page.
    #[serde(rename = "next_cursor", deserialize_with = "Option::deserialize")]
    pub next_cursor: Option<String>,
    #[serde(rename = "window")]
    pub window: Box<models::OccurrencePageWindow>,
    #[serde(rename = "scan")]
    pub scan: Box<models::OccurrencePageScan>,
    /// One entry per failure found in a recurrence rule: a malformed rule, one that floods the window, one with no start to unfold from, a timezone that does not resolve, or a `recurrence` holding something that is not an RFC 5545 property line. Absent when there were none. `item_id` names the row, and one row can appear more than once — a dropped rule line and a failure expanding what was left are two entries against the same id. A reported row may still appear in `data`: a rule that could not be applied leaves the row rendering as the single event its own times describe, and a rule missing one unreadable line still contributes every occurrence the rest of it produces. This reports on rules rather than on which rows are missing.
    #[serde(rename = "series_errors", skip_serializing_if = "Option::is_none")]
    pub series_errors: Option<Vec<models::OccurrencePageSeriesErrorsInner>>,
    /// Present and true when `series_errors` lists fewer failures than the request found. Both are counted in entries, so the comparison is exact. The array is capped at `scan.max_series_errors` rather than the read refused, so this is how the response says the list is partial; `scan.series_errors` carries the real total.
    #[serde(
        rename = "series_errors_truncated",
        skip_serializing_if = "Option::is_none"
    )]
    pub series_errors_truncated: Option<bool>,
    /// Present and true when the request stopped expanding series before it had walked them all, having spent `scan.max_unproductive_iterations` on expansions that returned no occurrence. `data` may be missing occurrences the unexpanded series held, and `scan.series_unexpanded` says how many were left. A narrower window does not recover it — the budget is spent walking rules from their own start, before the window is reached — so the moves are narrowing by `type` or fixing the rules `series_errors` names.
    #[serde(
        rename = "expansion_incomplete",
        skip_serializing_if = "Option::is_none"
    )]
    pub expansion_incomplete: Option<bool>,
}

impl OccurrencePage {
    pub fn new(
        data: Vec<models::Occurrence>,
        next_cursor: Option<String>,
        window: models::OccurrencePageWindow,
        scan: models::OccurrencePageScan,
    ) -> OccurrencePage {
        OccurrencePage {
            data,
            next_cursor,
            window: Box::new(window),
            scan: Box::new(scan),
            series_errors: None,
            series_errors_truncated: None,
            expansion_incomplete: None,
        }
    }
}
