/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OccurrencePageScan {
    /// Event rows this request read, summed across its passes. Two of the three cannot be narrowed by the window, so this grows with the size of the calendar rather than with the window asked for.
    #[serde(rename = "events_read")]
    pub events_read: i32,
    /// Occurrences returned, the length of `data`.
    #[serde(rename = "occurrences")]
    pub occurrences: i32,
    /// Ceiling `occurrences` is refused at. Reported on every successful read so a calendar approaching it is visible before a request is refused, rather than only once one is.
    #[serde(rename = "max_occurrences")]
    pub max_occurrences: i32,
    /// Failures this request found in recurrence rules, in the same unit as the `series_errors` array on the envelope: entries, not rows. One row can account for two — an unreadable line dropped from its rule is one failure, and expanding what was left then failing is another — so this is an upper bound on the number of rows to go and look at, and `item_id` is what a caller groups on to get the exact number. Counted across the event types this request read, and scoped to those and not to everything stored: a request narrowed by `type`, or a credential not permitted an event type, is told about the rules it read and nothing about the ones it did not, so a zero here is not a statement that the rest of the calendar is healthy. It counts everything this read detected, even when the array lists fewer, which is what lets a caller tell a handful of broken rules from a corrupt import without receiving the bytes of the larger one. Read it as a floor rather than as a certificate: it counts the ways of being broken this route knows how to recognize.
    #[serde(rename = "series_errors")]
    pub series_errors: i32,
    /// Longest list of failures the response will carry, counted in entries. Past this the list is capped and `series_errors_truncated` says so; the read still succeeds, because the list is a diagnostic beside the calendar and nothing in `data` depends on it. Entries rather than rows is the unit that matters here as well: a row reported twice consumes two of these.
    #[serde(rename = "max_series_errors")]
    pub max_series_errors: i32,
    /// Rule iterations this request spent on expansions that returned no occurrence: a rule that ended before the window or produced nothing in it, one too frequent to reach the window before the per-series iteration ceiling, and one refused for flooding the window — that last having produced occurrences the refusal then discarded, so this is what the expansion returned rather than what the rule computed. It is not a count of what reached `data`, which is assembled later behind a filter this does not consult. Only iterations are counted, so a series that fails before it iterates — an unreadable rule, a timezone that does not resolve — is reported in `series_errors` and charges nothing here. The unit the expansion ceiling is denominated in, reported on every successful read so a calendar approaching it is visible before it truncates one.
    #[serde(rename = "unproductive_iterations")]
    pub unproductive_iterations: i32,
    /// Ceiling `unproductive_iterations` stops expanding at. Iterations spent on series that do produce occurrences are not counted against it, so crossing it cannot be caused by a calendar having many meetings in it.
    #[serde(rename = "max_unproductive_iterations")]
    pub max_unproductive_iterations: i32,
    /// Series left unexpanded because `max_unproductive_iterations` was reached before they were reached. Zero on any read that finished expanding; above zero, `expansion_incomplete` is set on the envelope and `data` may be missing occurrences these series would have contributed.
    #[serde(rename = "series_unexpanded")]
    pub series_unexpanded: i32,
}

impl OccurrencePageScan {
    pub fn new(
        events_read: i32,
        occurrences: i32,
        max_occurrences: i32,
        series_errors: i32,
        max_series_errors: i32,
        unproductive_iterations: i32,
        max_unproductive_iterations: i32,
        series_unexpanded: i32,
    ) -> OccurrencePageScan {
        OccurrencePageScan {
            events_read,
            occurrences,
            max_occurrences,
            series_errors,
            max_series_errors,
            unproductive_iterations,
            max_unproductive_iterations,
            series_unexpanded,
        }
    }
}
