/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurgeItem409Response {
    #[serde(rename = "error")]
    pub error: Box<models::IdempotencyKeyInFlightRefusalError>,
    #[serde(rename = "current")]
    pub current: Box<models::ConflictSnapshot>,
}

impl PurgeItem409Response {
    pub fn new(
        error: models::IdempotencyKeyInFlightRefusalError,
        current: models::ConflictSnapshot,
    ) -> PurgeItem409Response {
        PurgeItem409Response {
            error: Box::new(error),
            current: Box::new(current),
        }
    }
}
