/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadViewChangedRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::ReadViewChangedRefusalError>,
}

impl ReadViewChangedRefusal {
    pub fn new(error: models::ReadViewChangedRefusalError) -> ReadViewChangedRefusal {
        ReadViewChangedRefusal {
            error: Box::new(error),
        }
    }
}
