/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceConnectorState200Response {
    /// The document as written.
    #[serde(rename = "state")]
    pub state: std::collections::HashMap<String, serde_json::Value>,
    /// When it was written.
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl ReplaceConnectorState200Response {
    pub fn new(
        state: std::collections::HashMap<String, serde_json::Value>,
        updated_at: String,
    ) -> ReplaceConnectorState200Response {
        ReplaceConnectorState200Response { state, updated_at }
    }
}
