/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettleTombstones200Response {
    /// The named tombstones as they stand after the write, in the order named. A key with no tombstone under `type` is left out.
    #[serde(rename = "tombstones")]
    pub tombstones: Vec<models::Tombstone>,
}

impl SettleTombstones200Response {
    pub fn new(tombstones: Vec<models::Tombstone>) -> SettleTombstones200Response {
        SettleTombstones200Response { tombstones }
    }
}
