/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StreamCapacityExhaustedRefusal {
    #[serde(rename = "error")]
    pub error: Box<models::StreamCapacityExhaustedRefusalError>,
}

impl StreamCapacityExhaustedRefusal {
    pub fn new(
        error: models::StreamCapacityExhaustedRefusalError,
    ) -> StreamCapacityExhaustedRefusal {
        StreamCapacityExhaustedRefusal {
            error: Box::new(error),
        }
    }
}
