/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tombstone {
    /// The link value, or the natural key's `source_id`.
    #[serde(rename = "key")]
    pub key: String,
    /// When the row holding the key was purged.
    #[serde(rename = "purged_at")]
    pub purged_at: String,
    /// The purge time, or a later time a key with write on the type moved it to through `POST /items/tombstones`.
    #[serde(rename = "remembered_until")]
    pub remembered_until: String,
}

impl Tombstone {
    pub fn new(key: String, purged_at: String, remembered_until: String) -> Tombstone {
        Tombstone {
            key,
            purged_at,
            remembered_until,
        }
    }
}
