/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 4
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypeResponse {
    #[serde(rename = "type")]
    pub r#type: Box<models::TypeDefinition>,
}

impl TypeResponse {
    pub fn new(r#type: models::TypeDefinition) -> TypeResponse {
        TypeResponse {
            r#type: Box::new(r#type),
        }
    }
}
