/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypeDefinitionInput {
    #[serde(rename = "fields")]
    pub fields: std::collections::HashMap<String, models::FieldDefinition>,
    /// Omit it to default to 1. A replacement carries the version it moves to.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<i32>,
    #[serde(rename = "parent", skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Structural roles this type plays, drawn from the closed vocabulary container. An entry outside it is refused `400 invalid_schema` naming `roles`.
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Vec<String>>,
    /// Field names this type requires, the alternative to `required: true` on each field. Both forms are taken and mean the same thing.
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<Vec<String>>,
    #[serde(rename = "compatible_with", skip_serializing_if = "Option::is_none")]
    pub compatible_with: Option<Box<models::TypeDefinitionInputCompatibleWith>>,
    #[serde(rename = "display_hints", skip_serializing_if = "Option::is_none")]
    pub display_hints: Option<Box<models::DisplayHints>>,
    #[serde(rename = "version_policy", skip_serializing_if = "Option::is_none")]
    pub version_policy: Option<models::VersionPolicy>,
    #[serde(rename = "merge_policy", skip_serializing_if = "Option::is_none")]
    pub merge_policy: Option<models::MergePolicy>,
    #[serde(rename = "id")]
    pub id: String,
}

impl TypeDefinitionInput {
    pub fn new(
        fields: std::collections::HashMap<String, models::FieldDefinition>,
        id: String,
    ) -> TypeDefinitionInput {
        TypeDefinitionInput {
            fields,
            version: None,
            parent: None,
            label: None,
            description: None,
            roles: None,
            required: None,
            compatible_with: None,
            display_hints: None,
            version_policy: None,
            merge_policy: None,
            id,
        }
    }
}
