/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TypeHasSubtypesOrTypeInUseRefusalError {
    #[serde(rename = "code")]
    pub code: Code,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl TypeHasSubtypesOrTypeInUseRefusalError {
    pub fn new(code: Code, message: String) -> TypeHasSubtypesOrTypeInUseRefusalError {
        TypeHasSubtypesOrTypeInUseRefusalError {
            code,
            message,
            details: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Code {
    #[serde(rename = "type_has_subtypes")]
    TypeHasSubtypes,
    #[serde(rename = "type_in_use")]
    TypeInUse,
}

impl Default for Code {
    fn default() -> Code {
        Self::TypeHasSubtypes
    }
}
