/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFolderRequest {
    /// The version the caller read, as on `PATCH /items/{id}`.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "search", skip_serializing_if = "Option::is_none")]
    pub search: Option<Box<models::FolderSearch>>,
    #[serde(rename = "defaults", skip_serializing_if = "Option::is_none")]
    pub defaults: Option<Box<models::FolderDefaults>>,
    /// Gitignore patterns, relative to the folder's root, naming the paths the folder takes; empty or absent takes every path.
    #[serde(rename = "include", skip_serializing_if = "Option::is_none")]
    pub include: Option<Vec<String>>,
    /// Gitignore patterns, relative to the folder's root, naming the paths the folder leaves alone.
    #[serde(rename = "ignore", skip_serializing_if = "Option::is_none")]
    pub ignore: Option<Vec<String>>,
    /// A map from type identifier to the directory, relative to the folder's root, where a new item of that type made elsewhere first appears.
    #[serde(rename = "first_placement", skip_serializing_if = "Option::is_none")]
    pub first_placement: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "removal_threshold", skip_serializing_if = "Option::is_none")]
    pub removal_threshold: Option<Box<models::FolderRemovalThreshold>>,
}

impl UpdateFolderRequest {
    pub fn new(version: i32) -> UpdateFolderRequest {
        UpdateFolderRequest {
            version,
            title: None,
            search: None,
            defaults: None,
            include: None,
            ignore: None,
            first_placement: None,
            removal_threshold: None,
        }
    }
}
