/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateItem409Response {
    #[serde(rename = "error")]
    pub error: Box<models::IdempotencyKeyInFlightRefusalError>,
    #[serde(rename = "current")]
    pub current: Box<models::ConflictSnapshot>,
    #[serde(rename = "ancestor")]
    pub ancestor: Box<models::ConflictSnapshot>,
    #[serde(rename = "conflicting_fields")]
    pub conflicting_fields: Vec<String>,
    #[serde(rename = "merge_policy")]
    pub merge_policy: models::MergePolicy,
    #[serde(rename = "requested_version")]
    pub requested_version: f64,
}

impl UpdateItem409Response {
    pub fn new(
        error: models::IdempotencyKeyInFlightRefusalError,
        current: models::ConflictSnapshot,
        ancestor: models::ConflictSnapshot,
        conflicting_fields: Vec<String>,
        merge_policy: models::MergePolicy,
        requested_version: f64,
    ) -> UpdateItem409Response {
        UpdateItem409Response {
            error: Box::new(error),
            current: Box::new(current),
            ancestor: Box::new(ancestor),
            conflicting_fields,
            merge_policy,
            requested_version,
        }
    }
}
