/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateWebhookRequest {
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<Events>>,
    #[serde(
        rename = "type_filter",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub type_filter: Option<Option<String>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl UpdateWebhookRequest {
    pub fn new() -> UpdateWebhookRequest {
        UpdateWebhookRequest {
            url: None,
            events: None,
            type_filter: None,
            active: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Events {
    #[serde(rename = "item.created")]
    ItemCreated,
    #[serde(rename = "item.updated")]
    ItemUpdated,
    #[serde(rename = "item.deleted")]
    ItemDeleted,
    #[serde(rename = "item.restored")]
    ItemRestored,
    #[serde(rename = "item.purged")]
    ItemPurged,
    #[serde(rename = "item.state_changed")]
    ItemStateChanged,
    #[serde(rename = "metadata.changed")]
    MetadataChanged,
    #[serde(rename = "edge.created")]
    EdgeCreated,
    #[serde(rename = "edge.updated")]
    EdgeUpdated,
    #[serde(rename = "edge.deleted")]
    EdgeDeleted,
}

impl Default for Events {
    fn default() -> Events {
        Self::ItemCreated
    }
}
