/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadBlob201Response {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "size_bytes")]
    pub size_bytes: f64,
}

impl UploadBlob201Response {
    pub fn new(hash: String, mime_type: String, size_bytes: f64) -> UploadBlob201Response {
        UploadBlob201Response {
            hash,
            mime_type,
            size_bytes,
        }
    }
}
