/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteConnectorAgreementsRequest {
    /// The process's own name for itself, opaque to the server, such as a UUID it chose at start.
    #[serde(rename = "process")]
    pub process: String,
    /// Records to write, each replacing the row's.
    #[serde(rename = "set", skip_serializing_if = "Option::is_none")]
    pub set: Option<Vec<models::WriteConnectorAgreementsRequestSetInner>>,
    /// Rows whose records to remove.
    #[serde(rename = "clear", skip_serializing_if = "Option::is_none")]
    pub clear: Option<Vec<String>>,
}

impl WriteConnectorAgreementsRequest {
    pub fn new(process: String) -> WriteConnectorAgreementsRequest {
        WriteConnectorAgreementsRequest {
            process,
            set: None,
            clear: None,
        }
    }
}
