/*
 * Marfa API
 *
 * Typed data layer for structured personal data
 *
 * The version of the OpenAPI document: 3
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WriteConnectorAgreementsRequestSetInner {
    #[serde(rename = "item_id")]
    pub item_id: String,
    #[serde(rename = "waiting")]
    pub waiting: bool,
    #[serde(rename = "record")]
    pub record: std::collections::HashMap<String, serde_json::Value>,
}

impl WriteConnectorAgreementsRequestSetInner {
    pub fn new(
        item_id: String,
        waiting: bool,
        record: std::collections::HashMap<String, serde_json::Value>,
    ) -> WriteConnectorAgreementsRequestSetInner {
        WriteConnectorAgreementsRequestSetInner {
            item_id,
            waiting,
            record,
        }
    }
}
